/**
 * Wizkoo Site Footer — single source of truth
 * Injects the canonical footer into #site-footer on every marketing page.
 * Runs synchronously (no DOMContentLoaded wrapper) so the footer is in
 * the DOM before any deferred scripts (e.g. nav.js sound attachment) fire.
 */
(function () {
  var el = document.getElementById('site-footer');
  if (!el) return;

  /* ── Scoped styles ──────────────────────────────────────────────────── */
  if (!document.getElementById('wf-styles')) {
    var style = document.createElement('style');
    style.id = 'wf-styles';
    style.textContent = [
      /* Founder bar */
      '#wizkoo-footer .wf-founder-bar{',
      '  padding:28px 48px 24px;',
      '  border-bottom:1px solid rgba(255,255,255,0.06);',
      '  text-align:center;',
      '}',
      '#wizkoo-footer .wf-founder-line{',
      '  font-family:\'Sora\',sans-serif;',
      '  font-weight:300;',
      '  font-size:clamp(0.88rem,1.6vw,1.05rem);',
      '  letter-spacing:-0.01em;',
      '  color:rgba(240,242,248,0.5);',
      '  margin:0;',
      '}',

      /* Base */
      '#wizkoo-footer{',
      '  background-color:#0C1020;',
      '  color:#F0F2F8;',
      '  border-top:1px solid rgba(255,255,255,0.04);',
      '}',

      /* ── Top grid — 4 columns (brand, nav, social, legal) ── */
      '#wizkoo-footer .wf-top{',
      '  padding:56px 48px 48px;',
      '  max-width:1200px;',
      '  margin:0 auto;',
      '  display:grid;',
      '  grid-template-columns:1fr 1fr 1fr auto;',
      '  gap:48px;',
      '  align-items:start;',
      '}',

      /* Col 1 — Brand */
      '#wizkoo-footer .wf-tagline{',
      '  font-family:Inter,sans-serif;',
      '  font-size:0.82rem;',
      '  color:#8C91A5;',
      '  line-height:1.6;',
      '  margin-top:12px;',
      '}',
      '#wizkoo-footer .wf-email{margin-top:8px;}',
      '#wizkoo-footer .wf-email a{',
      '  font-family:Inter,sans-serif;',
      '  font-size:0.72rem;',
      '  color:#8C91A5;',
      '  text-decoration:none;',
      '  transition:color 200ms ease;',
      '}',
      '#wizkoo-footer .wf-email a:hover{color:#F0F2F8;}',

      /* Col 2 — Nav */
      '#wizkoo-footer .wf-nav{',
      '  position:static!important;',
      '  height:auto!important;',
      '  background:transparent!important;',
      '  backdrop-filter:none!important;',
      '  -webkit-backdrop-filter:none!important;',
      '  padding:0!important;',
      '  box-shadow:none!important;',
      '  display:flex!important;',
      '  flex-direction:column!important;',
      '  gap:14px;',
      '  justify-content:flex-start!important;',
      '  border:none!important;',
      '}',
      '#wizkoo-footer .wf-nav a{',
      '  font-family:Inter,sans-serif;',
      '  font-size:0.88rem;',
      '  color:#F0F2F8;',
      '  text-decoration:none;',
      '  transition:color 200ms ease;',
      '}',
      '#wizkoo-footer .wf-nav a:hover{color:#C8CDDA;}',

      /* Col 3 — Social */
      '#wizkoo-footer .wf-social{',
      '  display:flex;',
      '  flex-direction:column;',
      '  gap:14px;',
      '}',
      '#wizkoo-footer .wf-social a{',
      '  font-family:Inter,sans-serif;',
      '  font-size:0.88rem;',
      '  color:#F0F2F8;',
      '  text-decoration:none;',
      '  transition:color 200ms ease;',
      '}',
      '#wizkoo-footer .wf-social a:hover{color:#C8CDDA;}',

      /* Col 4 — Legal (top section) */
      '#wizkoo-footer .wf-legal{',
      '  display:flex;',
      '  flex-direction:column;',
      '  align-items:flex-end;',
      '}',
      '#wizkoo-footer .wf-privacy{',
      '  font-family:"Space Mono",monospace;',
      '  font-size:0.5rem;',
      '  text-transform:uppercase;',
      '  letter-spacing:0.1em;',
      '  color:#8C91A5;',
      '  text-decoration:underline;',
      '  text-underline-offset:3px;',
      '  transition:color 200ms ease;',
      '}',
      '#wizkoo-footer .wf-privacy:hover{color:#F0F2F8;}',

      /* ── 3-column links section ── */
      '#wizkoo-footer .wf-links-section{',
      '  position:relative;',
      '  padding:60px 48px 40px;',
      '  border-top:1px solid transparent;',
      '  background-image:linear-gradient(90deg,transparent,rgba(232,175,56,0.15),transparent);',
      '  background-size:100% 1px;',
      '  background-repeat:no-repeat;',
      '  background-position:top;',
      '}',
      '#wizkoo-footer .wf-links-inner{',
      '  max-width:1200px;',
      '  margin:0 auto;',
      '  display:flex;',
      '  gap:80px;',
      '  align-items:start;',
      '}',
      '#wizkoo-footer .wf-col{',
      '  display:flex;',
      '  flex-direction:column;',
      '  gap:14px;',
      '}',
      '#wizkoo-footer .wf-col-label{',
      '  font-family:"Space Mono",monospace;',
      '  font-size:0.58rem;',
      '  letter-spacing:0.2em;',
      '  text-transform:uppercase;',
      '  color:rgba(250,250,250,0.25);',
      '  margin-bottom:6px;',
      '}',
      '#wizkoo-footer .wf-col a{',
      '  font-family:Inter,sans-serif;',
      '  font-size:0.8rem;',
      '  color:rgba(250,250,250,0.45);',
      '  text-decoration:none;',
      '  transition:color 250ms ease;',
      '  line-height:1.4;',
      '}',
      '#wizkoo-footer .wf-col a:hover{color:rgba(250,250,250,0.8);}',

      /* ── Bottom bar ── */
      '#wizkoo-footer .wf-bottom{',
      '  max-width:1200px;',
      '  margin:0 auto;',
      '  padding:32px 48px 40px;',
      '  border-top:1px solid rgba(255,255,255,0.06);',
      '  display:flex;',
      '  justify-content:space-between;',
      '  align-items:center;',
      '  flex-wrap:wrap;',
      '  gap:8px;',
      '}',
      '#wizkoo-footer .wf-copy{',
      '  font-family:"Space Mono",monospace;',
      '  font-size:0.58rem;',
      '  text-transform:uppercase;',
      '  letter-spacing:0.1em;',
      '  color:rgba(250,250,250,0.15);',
      '}',
      '#wizkoo-footer .wf-edu{',
      '  font-family:"Space Mono",monospace;',
      '  font-size:0.45rem;',
      '  text-transform:uppercase;',
      '  letter-spacing:0.1em;',
      '  color:#50556E;',
      '}',
      '#wizkoo-footer .wf-edu a{',
      '  color:#8C91A5;',
      '  text-decoration:underline;',
      '  text-underline-offset:3px;',
      '  transition:color 200ms ease;',
      '}',
      '#wizkoo-footer .wf-edu a:hover{color:#F0F2F8;}',

      /* ── Responsive — 768px ── */
      '@media(max-width:768px){',
      '  #wizkoo-footer .wf-top{',
      '    padding:48px 20px 40px;',
      '    grid-template-columns:1fr 1fr;',
      '    gap:32px;',
      '  }',
      '  #wizkoo-footer .wf-legal{align-items:flex-start;}',
      '  #wizkoo-footer .wf-links-section{padding:48px 20px 36px;}',
      '  #wizkoo-footer .wf-links-inner{',
      '    flex-direction:column;',
      '    gap:32px;',
      '  }',
      '  #wizkoo-footer .wf-bottom{',
      '    padding:24px 20px 32px;',
      '    flex-direction:column;',
      '    align-items:flex-start;',
      '    gap:6px;',
      '  }',
      '}',

      /* ── Responsive — 480px ── */
      '@media(max-width:480px){',
      '  #wizkoo-footer .wf-top{',
      '    grid-template-columns:1fr;',
      '    gap:28px;',
      '  }',
      '}'
    ].join('\n');
    document.head.appendChild(style);
  }

  /* ── Footer HTML ────────────────────────────────────────────────────── */
  el.innerHTML = [
    '<footer id="wizkoo-footer">',

    '  <!-- Founder bar -->',
    '  <div class="wf-founder-bar">',
    '    <p class="wf-founder-line">Founding families are in. You\u2019re next.</p>',
    '  </div>',

    '  <!-- Top: brand, quick nav, social, legal -->',
    '  <div class="wf-top">',

    '    <div class="wf-brand">',
    '      <a href="/" class="nav-wm" aria-label="Home">w<span class="i-fix">i</span>z<span class="k">k</span>o<span class="wm-dot">o</span></a>',
    '      <div class="wf-tagline">Weekly learning plans for families, ages 2&ndash;12.</div>',
    '      <div class="wf-email"><a href="mailto:hello@wizkoo.com">hello@wizkoo.com</a></div>',
    '    </div>',

    '    <nav class="wf-nav" aria-label="Site">',
    '      <a href="/plan">The Plan</a>',
    '      <a href="/games">The Games</a>',
    '      <a href="/methodology">The Science</a>',
    '    </nav>',

    '    <div class="wf-social">',
    '      <a href="https://instagram.com/heywizkoo" target="_blank" rel="noopener noreferrer">Instagram</a>',
    '      <a href="https://tiktok.com/@heywizkoo" target="_blank" rel="noopener noreferrer">TikTok</a>',
    '    </div>',

    '    <div class="wf-legal">',
    '      <a href="/privacy" class="wf-privacy">Privacy</a>',
    '    </div>',

    '  </div>',

    '  <!-- 3-column structured nav -->',
    '  <div class="wf-links-section">',
    '    <div class="wf-links-inner">',

    '      <div class="wf-col">',
    '        <div class="wf-col-label">Product</div>',
    '        <a href="/plan">The Plan</a>',
    '        <a href="/games">The Games</a>',
    '        <a href="/library">The Library</a>',
    '        <a href="/science">The Science</a>',
    '        <a href="/ages">The Ages</a>',
    '        <a href="/the-open-seat">The Open Seat</a>',
    '        <a href="/pricing">The Price</a>',
    '      </div>',

    '      <div class="wf-col">',
    '        <div class="wf-col-label">Learn More</div>',
    '        <a href="/about">About</a>',
    '        <a href="/esa">ESA &amp; Funding</a>',
    '        <a href="/scope">Scope &amp; Sequence</a>',
    '        <a href="/#faq">FAQ</a>',
    '      </div>',

    '      <div class="wf-col">',
    '        <div class="wf-col-label">Legal</div>',
    '        <a href="/privacy">Privacy Policy</a>',
    '        <a href="/terms">Terms of Service</a>',
    '        <a href="/contact">Contact</a>',
    '      </div>',

    '    </div>',
    '  </div>',

    '  <!-- Bottom bar -->',
    '  <div class="wf-bottom">',
    '    <span class="wf-copy">&copy; 2026 Wizkoo LLC</span>',
    '    <span class="wf-edu">Educator or co-op leader? <a href="mailto:hello@wizkoo.com">Get in touch.</a></span>',
    '  </div>',

    '</footer>'
  ].join('\n');
})();
