import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch4 = [
  {'idx':60,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'botany/seed science, climate change and food security, international cooperation, Arctic geography (Svalbard), agricultural biodiversity history','sl':'no','rationale':'Five doors: botany, climate, international policy, geography, agricultural history. Early-reader format limits depth; the civilization-insurance-policy meaning is present but not structurally embedded — the vault reads the same at both bands with different vocabulary, not different meaning.'},
  {'idx':61,'v2':5,'decision':'hold-5','doors':5,'door_list':'marine ecology, decomposition and nutrient cycling, deep-sea biology, life/death cycles in ecosystems, food web science','sl':'yes','rationale':'Five integrated doors: marine ecology, decomposition science, deep-sea biology, life cycles, food webs. Second layer holds: at 5-6 reads as remarkable animal feast on the whale body; at 7-9 the same whale fall reveals itself as a complete nutrient-recycling ecosystem that sustains deep-sea life for decades — fundamentally different meaning of the same whale.'},
  {'idx':62,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'American history (Lincoln era), crime/detective narrative, Secret Service and law enforcement history','sl':'n/a','rationale':'Three doors: history, crime narrative, law enforcement. Single band (10-12). Does not reach five-door threshold.'},
  {'idx':63,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Kenyan environmental history, Wangari Maathai biography, women civic leadership, tree species/ecology','sl':'no','rationale':'Per rubric: Mama Miti is the 4 anchor. Multi-domain reach is exceptional; book architecture stays at single-narrative level. Teacher can build a 5-tier unit but the book delivers linearly.'},
  {'idx':64,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'Ukrainian folk art (pysanky), cultural heritage preservation, biography','sl':'n/a','rationale':'Three doors: folk art, cultural preservation, biography. No subject tags to confirm additional domains. Does not reach five-door threshold.'},
  {'idx':65,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'Chinese-American cultural identity, immigration/diaspora experience, Southern American geography and culture, LGBTQ identity, coming-of-age','sl':'no','rationale':'Five doors: cultural identity, diaspora, Southern culture, LGBTQ, coming-of-age. Single band (10-12). OD only 141ch for an independent graphic novel; delivers identity layers simultaneously rather than as a structurally embedded second layer.'},
  {'idx':66,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Mexican cultural identity, family history and immigration, road-trip geography, intergenerational relationships','sl':'n/a','rationale':'Four doors: cultural identity, immigration, geography, family. No subject tags to confirm additional domains. Graphic memoir delivers identity content personally and directly.'},
  {'idx':67,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'engineering and design thinking, biology (natural models for invention), ecology, cross-disciplinary STEM, innovation history','sl':'no','rationale':'Five doors: engineering, biology, ecology, STEM integration, innovation. The biomimicry thesis — nature as evolutionary design database — is the books explicit framework, not a layer the older reader discovers. Second layer fails.'},
  {'idx':68,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'ornithology, long-distance migration ecology, coastal geography, conservation/advocacy, math (migration distances and survival rates)','sl':'no','rationale':'Five doors: ornithology, ecology, geography, conservation, math. Single band (10-12), advanced. OD only 102ch. The conservation-advocacy layer is the books explicit purpose rather than an embedded second layer.'},
  {'idx':69,'v2':5,'decision':'hold-5','doors':4,'door_list':'scientific ethics (NIMH animal experimentation), animal cognition/intelligence, social organization and governance, narrative fantasy','sl':'yes','rationale':'Four doors with exceptional second-layer depth (Where the Wild Things Are precedent applies). Second layer holds: at 10-12 reads as thrilling adventure with superintelligent rats; at older re-reading the ethics of intelligence enhancement — who owns it, what obligations follow, what makes consciousness worthy of rights — become the dominant reading of the same scenes. A 5 on second-layer depth, not door count.'},
  {'idx':70,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Antarctic ecology and wildlife, climate science (measurement context), robotics/technology in field science, geographic extremes','sl':'no','rationale':'Four doors: ecology, climate science, robotics, geography. Adventure-science format; the climate measurement purpose of the fieldwork is stated rather than embedded as a re-reading discovery.'},
  {'idx':71,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'shark biology, marine ecology and food web, scientific observation methodology, coastal geography (Farallon Islands), visual science art','sl':'no','rationale':'Five doors: shark biology, ecology, methodology, geography, visual art. OD only 107ch at picture-book density — too thin for the second-layer to be structurally embedded rather than surface-stated.'},
  {'idx':72,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'immunology and mRNA science, biography, scientific persistence through rejection, women in STEM history','sl':'no','rationale':'Four doors: immunology, biography, persistence, gender history. Early-reader format limits depth; the persistence-rewarded narrative is fully decoded on first reading.'},
  {'idx':73,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'visual narrative/wordless storytelling, environmental themes, imagination and wonder','sl':'n/a','rationale':'Three doors at picture-book density: visual narrative, environmental themes, imagination. Two-band span only (3-4, 5-6). Concept picture-book where the visual story is the entire experience.'},
  {'idx':74,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'cephalopod biology, animal cognition and intelligence science, marine ecology, animal behavior','sl':'no','rationale':'Four doors: biology, cognition science, ecology, behavior. Second layer fails: the geniuses-of-the-deep thesis — what octopus intelligence reveals about the nature of intelligence — is explicitly stated throughout rather than embedded as a re-reading discovery.'},
  {'idx':75,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'biography (James Earl Jones), speech and communication science, stuttering/disability, performing arts history','sl':'no','rationale':'Four doors: biography, speech science, disability, performing arts. Early-reader format limits concept depth; inspiring biography delivered in linear progression.'},
  {'idx':76,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'civic safety education, friendship and partnership, narrative irony (dog performs behind officers back)','sl':'n/a','rationale':'Three doors at picture-book density: civic safety, friendship, irony. Second layer absent: the irony of Glorias secret performances is visible and funny at 3-4; re-reading at 7-9 adds vocabulary to name the irony but reveals the same gag.'},
  {'idx':77,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'love of reading and meta-fiction, visual storytelling','sl':'n/a','rationale':'Two doors: meta-fiction and visual narrative. Books-bring-stories-to-life concept at picture-book density; singular idea executed with craft.'},
  {'idx':78,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'exponential mathematics, Indian cultural history and folk tale, social justice (peasant vs. ruler), geography, folk narrative structure','sl':'no','rationale':'Five doors: math, cultural history, social justice, geography, narrative. Second layer fails at picture-book density (OD 84ch): the doubling math is shown but the exponential growth concept is a delight at 5-6 and a named concept at 7-9 — more vocabulary, not different meaning of the same grains of rice.'},
  {'idx':79,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'freshwater pond ecology, above/below habitat structure, natural history narrative','sl':'n/a','rationale':'Three doors at picture-book density: freshwater ecology, habitat structure, natural history. OD only 80ch. The over/under structure is the single concept; well executed but narrow in domain scope.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch4:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 4 appended: {len(batch4)} rows')
holds = sum(1 for b in batch4 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch4 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch4 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
