import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch7 = [
  {'idx':120,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'autism and neurodivergence, animal science, biography, science of visual thinking','sl':'no','rationale':'Four doors: neurodivergence, animal science, biography, visual cognition. Second layer fails: inspiring representation narrative delivered explicitly; cognitive-difference framing is the books stated subject throughout.'},
  {'idx':121,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'urban history (1871 Chicago), fire science and urban infrastructure, social response to disaster, biography (multiple figures)','sl':'n/a','rationale':'Four doors: urban history, fire science, infrastructure, biography. Single band (10-12). Strong narrative nonfiction; does not reach five-door threshold.'},
  {'idx':122,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'rainforest ecology and biodiversity, environmental ethics, conservation science, geography (Amazon), social-emotional','sl':'no','rationale':'Five doors: ecology, ethics, conservation, geography, social-emotional. Second layer fails: each animal explicitly states what the tree means for their survival — both ecology and conservation ethics are stated at every reading age, not discovered by re-reading.'},
  {'idx':123,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'freshwater ecology, Great Lakes geography and natural history, water science and environmental history','sl':'n/a','rationale':'Three doors: freshwater ecology, geography, water science. Early-reader survey nonfiction; does not reach five-door threshold.'},
  {'idx':124,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'American history and diversity, civic identity','sl':'n/a','rationale':'Two doors: American history and civic identity. No subject tags confirmed. Concept picture-book about Americas diverse communities; singular idea without cross-domain substantive reach.'},
  {'idx':125,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'bee biology and ecology, poetry and language arts, natural cycles','sl':'n/a','rationale':'Three doors at picture-book density: bee science, poetry, natural cycles. Two-band span only (3-4, 5-6). Concept picture-book; does not carry the Artisan band with substantive depth.'},
  {'idx':126,'v2':5,'decision':'hold-5','doors':4,'door_list':'paleontology, history of science (error and correction over two centuries), scientific methodology (how knowledge evolves), dinosaur biology','sl':'yes','rationale':'Four doors with exceptional second-layer depth (Where the Wild Things Are precedent). Second layer holds: at 5-6 reads as fun story of scientists getting the dinosaurs wrong for 200 years; at 7-9 the same fossil record reveals the epistemology of science — how scientific knowledge accumulates, why errors persist, and how correction happens — a fundamentally different reading of the same bones.'},
  {'idx':127,'v2':5,'decision':'hold-5','doors':5,'door_list':'art history (Matisse and color theory), ornithology and bird color science, biography, visual art and illustration, French history','sl':'yes','rationale':'Five integrated doors: art history, bird science, biography, visual art, history. Second layer holds: at 5-6 reads as beautiful book about a boy who loved birds and color; at 7-9 the birds become the literal source code for Matisses mature color palette — same iridescent feathers, fundamentally different meaning (nature as aesthetic inheritance).'},
  {'idx':128,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'historical fiction and mapmaking, Southeast Asian geography, identity and authenticity under social class pressure','sl':'n/a','rationale':'Three doors: historical fiction, geography, identity. No subject tags confirmed. Does not reach five-door threshold on available evidence.'},
  {'idx':129,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'economics and business math, sibling social-emotional dynamics, narrative structure','sl':'n/a','rationale':'Three doors: economics/math, social-emotional, narrative. Single band (7-9). Limited cross-domain scope; the economics door is real but narrow alongside the personal sibling story.'},
  {'idx':130,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'navigation history, clockmaking and precision technology, maritime history and astronomy, British history, competition and political economy','sl':'no','rationale':'Five doors: navigation, technology, maritime history, astronomy, political economy. Single band (10-12). Harrisons biography delivers the longitude problem as problem-solving narrative; the imperial-power layer is present but not structurally embedded as a re-reading discovery.'},
  {'idx':131,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'Amazon geography and exploration, British colonial history, biography, anthropology and indigenous peoples, adventure narrative','sl':'no','rationale':'Five subjects confirmed. OD only 84ch — extremely thin. Single band (10-12), advanced. Too thin to confirm structural second-layer embedding.'},
  {'idx':132,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'art history (Mona Lisa and da Vinci), heist and detective narrative, French history, media history','sl':'no','rationale':'Four doors: art history, heist narrative, French history, media history. Second layer fails: the subtitle (Birth of a Global Celebrity) announces the media-theory thesis explicitly — both the heist drama and the celebrity-manufacturing argument are the books stated subject, not a layer the older reader discovers.'},
  {'idx':133,'v2':5,'decision':'hold-5','doors':5,'door_list':'engineering process and iterative design, frustration tolerance, design thinking and growth mindset, gender (girl as engineer), social-emotional (perfectionism and acceptance)','sl':'yes','rationale':'Per rubric: The Most Magnificent Thing is the Score 5 anchor. Reads as story at 4, as engineering frame at 7, as work-life metaphor at 10. Rubric-locked at 5.'},
  {'idx':134,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'historical mystery and detective reasoning, American racial history, family secrets and inheritance','sl':'n/a','rationale':'Three doors: mystery, racial history, family narrative. Single band (10-12). No subject tags confirmed. Does not reach five-door threshold.'},
  {'idx':135,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'migrant farmworker labor history, Mexican American cultural history, social justice','sl':'n/a','rationale':'Three doors: labor history, cultural history, social justice. No subject tags confirmed. Does not reach five-door threshold.'},
  {'idx':136,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (family dynamics, friendship), narrative structure','sl':'n/a','rationale':'Two doors: social-emotional and narrative. Single subject (social-emotional) confirmed. Beloved cozy family novel with minimal cross-domain reach; does not carry the Artisan band substantively.'},
  {'idx':137,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'urban ecology (tree planting and city transformation), social-emotional (generativity and promise), geography, visual art and illustration, environmental science','sl':'no','rationale':'Five subjects confirmed. Second layer fails: the promise-as-generativity metaphor and urban ecology transformation are explicitly stated in the books title and resolution — both layers accessible simultaneously to all readers.'},
  {'idx':138,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'marine biology (jellyfish), Arctic ecology, scientific fieldwork methodology, geography','sl':'n/a','rationale':'Four doors: marine biology, Arctic ecology, fieldwork methodology, geography. Early-reader format limits depth. Does not confirm five-door threshold.'},
  {'idx':139,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'astronomy (winter solstice), cultural history of solstice celebrations, geography, poetry and language arts','sl':'no','rationale':'Four subjects confirmed. OD only 120ch at picture-book density. Concept picture-book about winter solstice; four doors but too thin for second-layer structural embedding.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch7:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 7 appended: {len(batch7)} rows')
holds = sum(1 for b in batch7 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch7 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch7 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
