import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch6 = [
  {'idx':100,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'visual art/painting, space science and Apollo program, biography, history of human spaceflight','sl':'no','rationale':'Four doors: art, space science, biography, history. Second layer fails: the astronaut-turned-painter narrative is the explicit point; art and science as dual callings are stated rather than embedded as a re-reading layer.'},
  {'idx':101,'v2':5,'decision':'hold-5','doors':5,'door_list':'Shakespearean literary history, early modern book publishing/printing, cultural preservation theory, 17th-century English history, the philosophy of literary legacy','sl':'yes','rationale':'Five integrated doors: literary history, book history, cultural preservation, English history, literary philosophy. Second layer holds: at 7-9 reads as dramatic detective story of how Shakespeares plays survived; at 10-12 the same First Folio reveals itself as a meditation on which works get preserved and why, and whose cultural choices determine what survives — a fundamentally different meaning of the same artifact.'},
  {'idx':102,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'turtle biology and herpetology, conservation science, ecological relationships, natural history','sl':'no','rationale':'Four doors: biology, conservation, ecology, natural history. Sy Montgomery nature writing with multi-domain reach; conservation message delivered explicitly rather than embedded as a structural second layer.'},
  {'idx':103,'v2':5,'decision':'hold-5','doors':5,'door_list':'electrical engineering and wind energy, Malawian history and geography, innovation under scarcity, sustainability and appropriate technology, biography','sl':'yes','rationale':'Five integrated doors: engineering, African history, innovation, sustainability, biography. Second layer holds: at 7-9 reads as inspiring story of ingenious boy building a windmill from scrap; at 10-12 the same windmill reveals a portrait of structural poverty — the drought, the school fees he cannot pay, the library book as his only access to technical knowledge — making the same scenes read as appropriate technology and knowledge access, not just personal triumph.'},
  {'idx':104,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'entomology, neurodivergence (Tourette syndrome), social-emotional (difference and belonging), science as identity','sl':'no','rationale':'Four doors: entomology, neurodivergence, social-emotional, science identity. The representation of Tourette syndrome and the science-as-belonging message are stated explicitly; no structural second layer discovered through re-reading.'},
  {'idx':105,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'literacy and library access, Pakistani culture and geography, humanitarian dedication','sl':'n/a','rationale':'Three doors: literacy, Pakistani culture, humanitarian service. Early-reader format limits concept density; no subject tags confirmed. Does not reach five-door threshold.'},
  {'idx':106,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'astrophysics and stellar composition, women in science history, scientific discovery (hydrogen in stars), 20th-century institutional history','sl':'no','rationale':'Four doors: astrophysics, gender in science, scientific discovery, institutional history. Early-reader biography; Payne-Gaposchkin discovery delivered in inspiring-but-ignored linear sequence.'},
  {'idx':107,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'space science and Apollo 11 history, fear and courage (social-emotional), biography, the relationship between imagination and real achievement','sl':'no','rationale':'Four doors: space science, social-emotional, biography, imagination. Second layer fails: the fear-of-dark-to-astronaut arc is the explicit trajectory; the Apollo landing as transformative moment is stated rather than structurally embedded.'},
  {'idx':108,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'epistolary form, color theory, perspective-taking (each crayons voice), humor and satire','sl':'no','rationale':'Per rubric: Day the Crayons Quit is the 4 anchor. Multi-door and well-crafted; second layer fails because the gag is fully visible at 5-6 and re-reading at older age surfaces the same gag with more vocabulary. Not a different meaning — same meaning twice.'},
  {'idx':109,'v2':5,'decision':'hold-5','doors':5,'door_list':'paleontology, geophysics (asteroid impact science), cross-disciplinary scientific collaboration, history of scientific discovery, stratigraphy/geology','sl':'yes','rationale':'Five integrated doors: paleontology, geophysics, scientific collaboration, discovery history, geology. Second layer holds: at 7-9 reads as cool detective story — how did the dinosaurs die?; at 10-12 the Alvarez work reveals itself as a model of cross-disciplinary scientific reasoning (physics + geology + paleontology combined to solve a biological question) — the same discovery, different epistemological meaning.'},
  {'idx':110,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'civil rights history, Dr. King biography, social justice and civic action','sl':'n/a','rationale':'Three doors: civil rights, biography, social justice. Early-reader format; no subject tags. Does not reach five-door threshold.'},
  {'idx':111,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'cryptography, WWII history, teenage girls in wartime intelligence, biography (10 subjects)','sl':'n/a','rationale':'Four doors: cryptography, WWII, girls/womens history, biography. Single band (10-12). Linear biographical narrative of multiple codebreakers; does not reach five-door threshold with confirmed distinct domains.'},
  {'idx':112,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'evolutionary biology (Darwinism), Texas historical setting (1900), gender barriers to women in science, family dynamics and intergenerational conflict, social-emotional','sl':'no','rationale':'Five subjects confirmed. OD only 90ch for independent chapter-book — unusually thin. Single band (10-12). The Darwin-vs-tradition second layer is present but the thin OD suggests it may not be structurally embedded; conservative hold at 4.'},
  {'idx':113,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'social-emotional (belonging and freedom), philosophical perspective (dogs POV as lens on human world), narrative/literary craft','sl':'n/a','rationale':'Three doors: social-emotional, philosophical perspective, narrative craft. No subject tags confirmed. Does not reach five-door threshold.'},
  {'idx':114,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'marine biology/oceanography, conservation, biography, filmmaking/visual storytelling, geography (ocean exploration)','sl':'no','rationale':'Five doors confirmed by subjects. OD only 82ch at picture-book density — delivery too thin for structural second-layer embedding. Inspiring biography at picture-book density.'},
  {'idx':115,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'narrative science fiction (time travel), social-emotional, mystery/detective structure','sl':'n/a','rationale':'Three doors: science fiction, social-emotional, mystery. No subject tags confirmed. Does not reach five-door threshold on available evidence.'},
  {'idx':116,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'geometry/tessellation mathematics, women in mathematics history, sociology of amateur science, biography','sl':'no','rationale':'Four doors: geometry, gender in math, amateur science, biography. Second layer fails: the mathematical discovery (pentagonal tilings) is the books explicit subject, not a layer the older reader discovers — the same tiles reveal their mathematical significance as stated knowledge rather than structurally embedded re-reading.'},
  {'idx':117,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'biology (aging, jellyfish immortality), social-emotional (family across generations), narrative structure, science as plot catalyst','sl':'n/a','rationale':'Four doors: biology, social-emotional, narrative, science. Single band (10-12). The science of aging is plot-catalyst rather than a domain the book opens for substantive engagement; social-emotional and narrative dominate.'},
  {'idx':118,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'WWII post-war recovery (US and France), humanitarian aid history, American history, cross-cultural friendship','sl':'no','rationale':'Four doors: post-war history, humanitarian aid, American history, cross-cultural connection. Early-reader format; friendship train narrative delivered in linear humanitarian-hope sequence.'},
  {'idx':119,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'entomology, scientific illustration as historical documentation, women in science (17th century), European natural history, biography','sl':'no','rationale':'Five subjects confirmed. Single band (10-12). OD 123ch. The scientific-documentation-through-illustration reading requires the reader to bring historical frame from outside the book; the second layer is constructed rather than naturally embedded.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch6:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 6 appended: {len(batch6)} rows')
holds = sum(1 for b in batch6 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch6 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch6 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
