import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch8 = [
  {'idx':140,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'space history, womens history, biography (six subjects), engineering and astronaut training','sl':'n/a','rationale':'Four doors: space history, gender history, biography, engineering. Single band (10-12). Multi-biography format; does not confirm five-door threshold on distinct substantive domains.'},
  {'idx':141,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'ocean ecology, geography, rhyme/language arts, social-emotional (small creature/big world)','sl':'no','rationale':'Per rubric: The Snail and the Whale is the 4 anchor. Second layer minimal — the rescue arc is fully visible at the target age. Genuinely strong, multi-domain, well-crafted. Solid 4.'},
  {'idx':142,'v2':5,'decision':'hold-5','doors':5,'door_list':'Black American history, poetry and literary craft, visual art, social-emotional (resilience and pride), civil rights history','sl':'yes','rationale':'Five integrated doors: Black history, poetry, visual art, social-emotional, civil rights. Second layer holds: at 7-9 reads as a powerful tribute to Black American resilience; at 10-12 the specific historical allusions embedded in the verse — figures named and moments referenced — become legible as a dense network of historical knowledge the younger reader senses but cannot decode. Same poem, different historical legibility.'},
  {'idx':143,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'earth science and geology (salt mine and lake drainage), industrial disaster science, Louisiana history, environmental consequences','sl':'no','rationale':'Four doors: geology, industrial disaster, Louisiana history, environment. No subject tags confirmed. Second layer possible (systems failure vs. disaster drama) but not structurally confirmed without subject data.'},
  {'idx':144,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'water scarcity and access, African geography, environmental science, social-emotional','sl':'no','rationale':'Four subjects confirmed. OD only 95ch at picture-book density. Water-walk narrative states the scarcity message explicitly; thin delivery limits structural second-layer embedding.'},
  {'idx':145,'v2':5,'decision':'hold-5','doors':4,'door_list':'mystery and detective puzzle-solving, American capitalism and identity reinvention, social dynamics (diverse cast), literary intertextuality (A Wrinkle in Time)','sl':'yes','rationale':'Four doors with exceptional second-layer depth (Where the Wild Things Are precedent). Second layer holds: at 10-12 reads as a brilliantly constructed mystery puzzle; at older re-reading the same scenes reveal a satire of American identity — Sam Westing inhabits multiple personas, each heir embodies a version of the American dream, and the game itself is a commentary on inheritance and reinvention. Same mystery, fundamentally different social meaning.'},
  {'idx':146,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'American colonial history, Puritan religious culture, womens independence in colonial context, historical fiction craft','sl':'n/a','rationale':'Four doors: colonial history, religion, gender, historical craft. Single band (10-12). Single subject (history) confirmed. Linear historical narrative at 4.'},
  {'idx':147,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (purpose and transitions), community and belonging','sl':'n/a','rationale':'Two doors: social-emotional and community. No subject tags confirmed. Picture-book concept about finding purpose and place; narrow domain scope. Also flagged in Item J for text density confirmation.'},
  {'idx':148,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'African American literary history, biography (Langston Hughes and peers), poetry/literary culture','sl':'n/a','rationale':'Three doors: literary history, biography, poetry culture. No subject tags confirmed. Literary biography at picture-book density; does not reach five-door threshold.'},
  {'idx':149,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'Japanese American incarceration, civil liberties, WWII American history, memoir and testimony, childhood experience of systemic injustice','sl':'no','rationale':'Five doors: incarceration history, civil liberties, WWII, memoir, childhood testimony. Single band (10-12). Delivers all layers in linear personal testimony sequence; calibrates with Mama Miti anchor (multi-domain reach, linear delivery).'},
  {'idx':150,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'social-emotional (fear and courage), intergenerational relationship, cooking/cultural recipe','sl':'n/a','rationale':'Three doors at picture-book density: social-emotional, intergenerational, cooking. Second layer absent: the fear-of-thunder arc is fully decoded at 3-4; the cake-baking process is the mechanism for courage, stated explicitly. No different meaning at older reading.'},
  {'idx':151,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'microbiology, math (scale and quantity), ecology','sl':'n/a','rationale':'Three doors at picture-book density: microbiology, math, ecology. OD only 110ch. Concept book about the microbial world — single idea (microbes are everywhere and do important work) executed with craft. Calibrates with Press Here anchor for concept books where the concept is the book.'},
  {'idx':152,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'folk tale narrative structure, agriculture and plant biology (tops and bottoms), trickster/cleverness theme','sl':'n/a','rationale':'Three doors at picture-book density: folk tale, botany, trickster narrative. The tops-and-bottoms agricultural trick is clever but singular; second layer absent — the trick is the punchline at every age.'},
  {'idx':153,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'astronomy and data sonification, disability and accessibility in science, scientific methodology, biography','sl':'no','rationale':'Four doors: astronomy, disability/accessibility, scientific methodology, biography. Second layer fails: sonification — converting light data to sound — is the books explicit scientific subject, stated as the method throughout; not a discovered second layer.'},
  {'idx':154,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Kenyan environmental history, womens civic leadership, ecology (tree planting), geography','sl':'no','rationale':'Four subjects confirmed. OD only 75ch. Calibrates with Mama Miti 4 anchor; same Wangari Maathai subject at picture-book density with thin delivery.'},
  {'idx':155,'v2':5,'decision':'hold-5','doors':5,'door_list':'Chinese American cultural identity, immigration experience and belonging, botany (watercress), social-emotional (shame and inherited pride), intergenerational memory','sl':'yes','rationale':'Five integrated doors: cultural identity, immigration, botany, social-emotional, intergenerational memory. Second layer holds: at 5-6 reads as story of girl embarrassed by parents gathering weeds; at 7-9 the same watercress reveals itself as survival food carrying the memory of famine and displacement — the parents eat it because they once had to, not just because they want to. Same plant, fundamentally different meaning across reading ages.'},
  {'idx':156,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'Japanese American incarceration, civil liberties history, citizenship and identity','sl':'n/a','rationale':'Three doors: incarceration history, civil liberties, citizenship/identity. Early-reader format limits depth. Does not reach five-door threshold.'},
  {'idx':157,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'indigenous environmental activism, water science, history (Dakota Access Pipeline context), social-emotional','sl':'no','rationale':'Four subjects confirmed. OD only 81ch at picture-book density. The water protection message is stated explicitly throughout; thin delivery limits structural embedding.'},
  {'idx':158,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'evolutionary biology and deep time, natural history narrative, identity and belonging (all life as kin), science of life origins','sl':'no','rationale':'Four doors: evolution, natural history, philosophy of kinship, origin science. Second layer fails: the all-life-is-kin conclusion is the books stated thesis — the evolutionary lineage is the explicit subject, not a layer discovered through re-reading.'},
  {'idx':159,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'Chinese mythology and folklore, geography (Chinese historical settings), history (dynastic China), language-arts (storytelling tradition), science (natural phenomena in myth)','sl':'no','rationale':'Five subjects confirmed. OD only 106ch for independent chapter-book — too thin to confirm structural second-layer embedding. The embedded folk tales create texture but their re-reading layer is not confirmed by the thin OD.'},
  {'idx':160,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'mystery and detective narrative, time travel as science concept, literary intertextuality (A Wrinkle in Time)','sl':'no','rationale':'Three doors: mystery, science concept, literary reference. Single band (10-12). Second layer is twist-reveal rather than age-developmental — re-reading the book knowing the ending changes the reading, but this is not the rubric second-layer test (younger vs. older reader getting different meaning of same scenes).'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch8:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 8 appended: {len(batch8)} rows')
holds = sum(1 for b in batch8 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch4 if b['decision']=='drop-to-4') if False else sum(1 for b in batch8 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch8 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
