import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch2 = [
  {'idx':20,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Fibonacci math history, medieval European history, biography, Fibonacci patterns in nature','sl':'no','rationale':'Four doors: math history, European history, biography, natural science. OD only 92ch at picture-book density; the Fibonacci-in-nature connection is present but thinly delivered.'},
  {'idx':21,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Renaissance art history, apprenticeship/craft tradition, Italian history, religious iconography','sl':'no','rationale':'Four doors: art history, craft tradition, Italian history, religion. Graphic novel format; Renaissance political/religious context not confirmed as structurally embedded for re-reading discovery.'},
  {'idx':22,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'WWII post-war recovery, cross-cultural friendship, humanitarian aid, Dutch geography/history','sl':'no','rationale':'Four doors: WWII history, recovery, friendship, geography. Second layer fails: Katje explains through her letters what each gift means, making both the friendship and humanitarian framing accessible simultaneously to all readers.'},
  {'idx':23,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Depression-era America, 1936 Berlin Olympics and Nazi propaganda, rowing/athletics, teamwork psychology','sl':'no','rationale':'Four doors: history, athletics, political context, teamwork. Single band (10-12). Delivers the Berlin Olympics propaganda layer explicitly rather than embedded as re-reading second layer.'},
  {'idx':24,'v2':5,'decision':'hold-5','doors':6,'door_list':'Civil Rights history, Black American experience, family relationships, poetry/language-arts as form, geography (South to NYC), identity formation','sl':'yes','rationale':'Six integrated doors: civil rights, identity, family, poetry, geography, Black cultural history. Second layer holds: at 10-12 the verse reads as narrative; at older re-reading the compression and craft choices — what the verse omits, how rhythm creates emphasis — become legible as a separate layer of meaning the younger reader cannot yet access.'},
  {'idx':25,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'construction/engineering, family identity/values, self-sufficiency ethic, math/planning','sl':'no','rationale':'Four doors: construction, family values, self-sufficiency, math. Second layer fails: the self-sufficiency theme and family-builds-together meaning are fully visible on first reading; re-reading adds appreciation, not new meaning.'},
  {'idx':26,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'climate science history, women in science, 19th-century American history, scientific method','sl':'no','rationale':'Four doors: climate science, women in STEM, history, scientific method. Early-reader format limits concept depth; the historical-injustice layer (Foote ignored despite correct findings) is stated rather than structurally embedded.'},
  {'idx':27,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'Lincoln assassination history, manhunt/detective narrative, Civil War aftermath','sl':'n/a','rationale':'Three doors: history, narrative tension, Civil War context. Single band (10-12). Does not reach five-door threshold.'},
  {'idx':28,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'labor rights/collective bargaining (implicit), absurdist humor, negotiation/ultimatum structure, animal-as-social-commentary','sl':'no','rationale':'Four doors: labor satire, humor, narrative structure, social commentary. Second layer fails: the labor-negotiation gag is fully visible at 3-4 as funny and at 7-9 as cleverly named — more vocabulary, same fundamental gag. Calibrates with Day the Crayons Quit anchor.'},
  {'idx':29,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'cryptography, WWII history, womens history, mathematics/linguistics','sl':'no','rationale':'Four doors: cryptography, WWII, gender history, math. Single band (10-12). Womens role in codebreaking is the explicit subject; delivered linearly.'},
  {'idx':30,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'mathematics/pattern recognition, visual art, family relationship, social-emotional persistence','sl':'no','rationale':'Four doors: math, art, family, persistence. Second layer fails: math-is-everywhere message stated explicitly; second band only extends to 5-6, limiting re-reading span.'},
  {'idx':31,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'space history, mathematics, civil rights/racial barriers, gender barriers, biography','sl':'no','rationale':'Five doors: space, math, racial history, gender history, biography. OD only 85ch at picture-book density; calibrates with Mama Miti anchor (biography with multi-domain reach but linear delivery). Delivery too thin to earn second layer.'},
  {'idx':32,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'indigenous culture/Tarahumara tradition, marathon athletics, Copper Canyon geography/ecology, biography','sl':'no','rationale':'Four doors: indigenous culture, athletics, ecology, biography. Inspiring biography with multi-domain reach delivered in linear sequence; no structural second layer confirmed.'},
  {'idx':33,'v2':5,'decision':'hold-5','doors':5,'door_list':'medical history, scientific epistemology (failure as knowledge), biology, history of discovery, philosophy of science','sl':'yes','rationale':'Five integrated doors: medical history, epistemology, biology, discovery history, philosophy. Second layer holds: at 7-9 the failed experiments read as dramatic gross stories; at 10-12 the pattern across failures becomes visible as a system — iteration, hypothesis, falsifiability — revealing a different meaning of the same stories.'},
  {'idx':34,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'earthworm ecology, diary literary form, humor/perspective-taking','sl':'n/a','rationale':'Three doors at picture-book density: ecology, diary form, humor. No second layer; the worm-perspective gag is fully decoded at 3-4. Less substantial than the Day the Crayons Quit 4 anchor; calibrates closer to concept-book territory.'},
  {'idx':35,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'genetics/biology, history of science, Mendel biography, evolutionary biology','sl':'no','rationale':'Four doors: genetics, scientific history, biography, evolution. Single band (10-12), advanced. Social implications of genetics (eugenics) are present but narrated linearly rather than as a structurally embedded second layer.'},
  {'idx':36,'v2':5,'decision':'hold-5','doors':5,'door_list':'palindromic literary structure, narrative perspective, visual storytelling, refugee/displacement experience, language/wordplay','sl':'yes','rationale':'Five integrated doors: literary structure, perspective, visual art, refugee experience, language. Second layer is structurally embedded: the SAME pages read as journey away (forward) and journey home (backward) — two different meanings in identical illustrations, discoverable only by re-reading in reverse.'},
  {'idx':37,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'disaster meteorology, American history, racial inequality in disaster response, New Orleans history/culture','sl':'no','rationale':'Four doors: disaster science, American history, racial inequality, cultural history. Single band (10-12). Graphic novel delivers racial-inequality layer visually and simultaneously with the disaster narrative rather than as a re-reading discovery.'},
  {'idx':38,'v2':5,'decision':'hold-5','doors':5,'door_list':'music/drumming, gender barriers in Cuban culture, 1930s Cuban history, Chinese-African-Cuban cultural identity, artistic persistence','sl':'yes','rationale':'Five integrated doors: music, gender, history, cultural identity, persistence. Second layer holds: at 3-4 reads as girl wants to drum and succeeds; at 7-9 the gender prohibition, racial/ethnic identity, and historical Cuban cultural norms become visible as the real subject of the same scenes.'},
  {'idx':39,'v2':5,'decision':'hold-5','doors':5,'door_list':'space science/orbital mechanics, photography as document, environmental movement history, Apollo program, philosophical shift in human self-perception','sl':'yes','rationale':'Five integrated doors: space science, photography, environmentalism, history, philosophy. Second layer holds: at 7-9 the Earthrise photograph reads as a stunning space image; at 10-12 the moment humans first saw Earth as a whole — fragile, borderless, shared — reveals a philosophical and environmental meaning the younger reader cannot yet access.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch2:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 2 appended: {len(batch2)} rows')
holds = sum(1 for b in batch2 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch2 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch2 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
