import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score5 = [b for b in data if b['current_score'] == 5]

batch5 = [
  {'idx':80,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'labor history, radiation physics, womens history, workplace safety and law, industrial history','sl':'no','rationale':'Five doors: labor, physics, gender history, law, industrial history. Single band (10-12). The radium-workers-fight-back narrative is powerful and multi-domain but delivered linearly; the legal and scientific layers are explicit throughout.'},
  {'idx':81,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'space history, mathematics, civil rights/racial history, gender history, autobiography/memoir','sl':'no','rationale':'Five doors: space, math, racial history, gender history, memoir. Single band (10-12). Autobiography format delivers all layers simultaneously and explicitly — the intersection of race, gender, and science is the stated subject throughout.'},
  {'idx':82,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'cave geology and spelunking, rescue diving science, international cooperation dynamics, psychology under extreme conditions','sl':'n/a','rationale':'Four doors: geology, rescue science, international cooperation, psychology. Single band (10-12). Does not confirm five-door threshold; immediate rescue narrative delivers drama and science in linear sequence.'},
  {'idx':83,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'imaginative play and community building, desert geography, childhood memory and retrospection','sl':'no','rationale':'Three doors: play/community, geography, memory. Second layer present but door count insufficient — the retrospective framing (Roxaboxen is still there) creates a meditation on childhood memory but requires only 3 doors at picture-book density to do it.'},
  {'idx':84,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'earth science (underground layers), persistence and near-miss narrative, visual irony, subtle parallel-world ending','sl':'near-miss','rationale':'Four doors: earth science, persistence, visual irony, narrative. Second layer near-miss: the subtle visual differences at the endings close may reveal a parallel-world reading to attentive older readers, but the structural embedding requires noticing a visual detail rather than a re-reading of meaning — more visual-acuity test than genuine second layer.'},
  {'idx':85,'v2':5,'decision':'hold-5','doors':5,'door_list':'neuroscience and neural anatomy, art and scientific illustration, biography, Spanish history and culture, scientific methodology (observation as discovery)','sl':'yes','rationale':'Five integrated doors: neuroscience, art, biography, history, methodology. Second layer holds: at 5-6 Cajals drawings read as beautiful art of mysterious shapes; at 7-9 the same drawings reveal themselves as the discovery (neurons are individual cells, not a continuous net) — art and scientific breakthrough are structurally identical objects in this book.'},
  {'idx':86,'v2':4,'decision':'drop-to-4','doors':4,'door_list':'Kenyan environmental history, womens civic leadership, tree planting ecology, post-colonial African history','sl':'no','rationale':'Four doors: environmental history, leadership, ecology, post-colonial history. Calibrates with Mama Miti 4 anchor — same Wangari Maathai subject treated at picture-book density in linear biographical sequence.'},
  {'idx':87,'v2':5,'decision':'hold-5','doors':5,'door_list':'genetics and molecular biology (transposable elements), womens history in science, scientific methodology and peer rejection, agricultural science (corn genetics), biography','sl':'yes','rationale':'Five integrated doors: genetics, gender in science, methodology, agriculture, biography. Second layer holds: at 5-6 reads as inspiring biography of woman who studied corn for decades and was ignored; at 7-9 the jumping genes concept (genetic elements that move between chromosomes, revolutionizing understanding of heredity) becomes legible as a scientific revolution, not just a discovery — same corn plants, fundamentally different biological meaning.'},
  {'idx':88,'v2':5,'decision':'hold-5','doors':5,'door_list':'photography as historical document, Japanese American incarceration history, civil liberties and racial justice, WWII American history, visual analysis and photographic theory','sl':'yes','rationale':'Five integrated doors: photography, incarceration history, civil liberties, WWII, visual theory. Second layer holds: at 7-9 the three photographers produce powerful historical images; at 10-12 the same photographs reveal what each photographer chose to show and hide and why (government assignment, insider witness, humanizing beauty) — photographic theory makes the same images mean differently at different reading ages.'},
  {'idx':89,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'civil rights history (pre-Brown desegregation), legal process/civics, California history, Mexican American history, social justice','sl':'no','rationale':'Five doors: civil rights, law, California history, Mexican American history, social justice. OD only 82ch at picture-book density — too thin for structural second-layer embedding. The legal and historical layers are labeled but not woven as re-reading layers.'},
  {'idx':90,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'shark science, marine biology, biography, gender history (woman in male-dominated field), ocean geography','sl':'no','rationale':'Five doors: shark science, marine biology, biography, gender history, geography. OD only 117ch at picture-book density. Inspiring biography with multi-domain reach; calibrates with Mama Miti 4 anchor (thin delivery).'},
  {'idx':91,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'astronomy and cosmology, womens history in science, dark matter physics, scientific methodology, biography','sl':'no','rationale':'Five doors: astronomy, gender in science, dark matter physics, methodology, biography. Early-reader format limits depth; the dark matter physics concept likely receives summary treatment rather than structural embedding across re-reading ages.'},
  {'idx':92,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'Shackleton expedition, Antarctic geography, survival science, maritime history, social-emotional (team cohesion under crisis)','sl':'no','rationale':'Five subjects confirmed. OD only 69ch — extremely thin for advanced independent level. Single band (10-12). Delivers multi-domain content but too thin to embed a structural second layer.'},
  {'idx':93,'v2':5,'decision':'hold-5','doors':5,'door_list':'maritime history, multiple scientific domains (per shipwreck: oceanography, geology, biology, chemistry), scientific methodology, naval history, disaster science','sl':'yes','rationale':'Five integrated doors: maritime, cross-domain science, methodology, naval history, disaster science. Second layer holds: at 7-9 each wreck reads as dramatic disaster story; at 10-12 the same disasters reveal themselves as unintentional scientific experiments that advanced knowledge — same ships, fundamentally different meaning.'},
  {'idx':94,'v2':5,'decision':'hold-5','doors':5,'door_list':'disability and accessibility history, literacy and writing systems, biography, 19th-century French history, scientific invention process','sl':'yes','rationale':'Five integrated doors: disability history, literacy, biography, French history, invention. Second layer holds: at 5-6 reads as inspiring story of blind boy who created a reading system for the blind; at 7-9 the Braille grid reveals itself as an elegant information-encoding system — six dots encoding 64 possible patterns — transforming the same dots from triumph narrative into mathematical design insight.'},
  {'idx':95,'v2':4,'decision':'drop-to-4','doors':3,'door_list':'social-emotional (colorism and self-acceptance), visual art/illustration, African heritage and identity','sl':'no','rationale':'Three doors: social-emotional, art, cultural heritage. The night-sky metaphor (night and day story) is woven into the surface narrative as the plot resolution, not as a second layer the older reader discovers independently — both metaphor and lesson are accessible simultaneously.'},
  {'idx':96,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'mathematics (spirals, Fibonacci), natural science, visual art','sl':'n/a','rationale':'Three doors at picture-book density: math, natural science, visual art. OD only 67ch. Single concept (spirals in nature) executed with craft; the same type of concept book as Press Here anchor — brilliant single idea at picture-book density.'},
  {'idx':97,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'civil rights history, education as civil rights tool, biography, citizenship and voting rights, African American history','sl':'no','rationale':'Five doors: civil rights, education, biography, voting rights, African American history. Early-reader format limits depth; biography of Septima Clark delivered in linear sequence at early-reader density.'},
  {'idx':98,'v2':4,'decision':'drop-to-4','doors':5,'door_list':'autism and neurodivergence, animal science and behavior, agricultural engineering, biography, social-emotional','sl':'no','rationale':'Five subjects confirmed. OD only 82ch for independent-level book — extremely thin. Single band (10-12). Inspiring biography delivered in too-thin form to structurally embed a second layer.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch5:
        bk = score5[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 5, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'Batch 5 appended: {len(batch5)} rows')
holds = sum(1 for b in batch5 if b['decision']=='hold-5')
drop4 = sum(1 for b in batch5 if b['decision']=='drop-to-4')
drop3 = sum(1 for b in batch5 if b['decision']=='drop-to-3')
print(f'  hold-5: {holds} | drop-to-4: {drop4} | drop-to-3: {drop3}')
