import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score4 = [b for b in data if b['current_score'] == 4]

batch = [
  {'idx':100,'v2':4,'decision':'hold-4','doors':3,'door_list':'animal science and biology (owl, porcupine, and woodland species), ecological land use and agricultural change, adventure narrative craft','sl':'n/a','rationale':'Three doors: animal science/biology, ecological land use, adventure narrative. OD confirms owl hunting behaviors and agricultural land use as real content; three substantive doors in single-band novel.'},
  {'idx':101,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'interactive digital literacy concept (input-output), mathematics and logical cause-and-effect','sl':'n/a','rationale':'Two doors: interactive/digital literacy concept, mathematical cause-effect. Rubric-noted Score 3 anchor; concept book where the concept is the book. Does not reach three-door threshold.'},
  {'idx':102,'v2':4,'decision':'hold-4','doors':3,'door_list':'disability representation and chronic illness, social-emotional (resilience, belonging, and authentic identity), fantasy and magical realism','sl':'n/a','rationale':'Three doors: disability representation, social-emotional resilience, fantasy/magical realism. 388ch at two bands with three confirmed cross-domain doors.'},
  {'idx':103,'v2':4,'decision':'hold-4','doors':3,'door_list':'earth science and water cycle, social-emotional perspective-taking (same rain, different reaction), language arts and poetry','sl':'n/a','rationale':'Three doors confirmed by subject tags (language-arts, science, social-emotional). 379ch at two young bands with three confirmed cross-domain doors.'},
  {'idx':104,'v2':4,'decision':'hold-4','doors':3,'door_list':'medieval fantasy world-building and survival skills (archery, tracking), social-emotional (belonging, courage, and found-identity), adventure narrative','sl':'n/a','rationale':'Three doors: medieval fantasy/survival skills, social-emotional, adventure narrative. 276ch single-band adventure novel with three confirmed cross-domain doors.'},
  {'idx':105,'v2':4,'decision':'hold-4','doors':3,'door_list':'social-emotional (social media, popularity, and authentic identity), school community and friendship dynamics, narrative and character development','sl':'n/a','rationale':'Three doors: social media/social-emotional, school community, narrative craft. 328ch at two bands with three confirmed cross-domain doors.'},
  {'idx':106,'v2':4,'decision':'hold-4','doors':4,'door_list':'American Revolutionary War history, women\'s roles in the Revolutionary period, biography of Mary Katherine Goddard, social justice and civic action','sl':'n/a','rationale':'Four doors: Revolutionary history, women\'s history, biography, social justice. History tag confirmed; 347ch single-band biography with four confirmed substantive cross-domain doors.'},
  {'idx':107,'v2':4,'decision':'hold-4','doors':3,'door_list':'engineering design process and iterative problem-solving, WWII history and Rosie the Riveter cultural connection, social-emotional growth mindset and creative courage','sl':'n/a','rationale':'Three doors: engineering process, WWII history (Rosie the Riveter), growth mindset. Companion to Iggy Peck Architect (Score 4 anchor); three confirmed doors despite thin OD. Same author-series calibration.'},
  {'idx':108,'v2':4,'decision':'hold-4','doors':3,'door_list':'folk tale narrative structure and literary craft, textile history and medieval spinning trade, narrative agency and women\'s wit in folk tradition','sl':'n/a','rationale':'Three doors: folk tale craft, textile/economic history (spinning), women\'s agency in narrative. 372ch at two bands; fairy tale with genuine historical and craft domain reach.'},
  {'idx':109,'v2':4,'decision':'hold-4','doors':3,'door_list':'Muslim cultural heritage and hospitality traditions, social-emotional (hospitality, boundaries, and unexpected guests), humor and narrative structure','sl':'n/a','rationale':'Three doors: Islamic cultural heritage, social-emotional, narrative humor. 291ch at two bands with genuine cultural and social-emotional cross-domain reach.'},
  {'idx':110,'v2':4,'decision':'hold-4','doors':4,'door_list':'marine biology and ocean science, evolutionary biology and origins of life (ocean as ancestor), poetry and language arts, philosophy of ecological kinship','sl':'n/a','rationale':'Four doors: marine biology, evolutionary origins, poetry, philosophy of kinship. Science tag confirmed; 324ch at two bands with four confirmed cross-domain doors.'},
  {'idx':111,'v2':4,'decision':'hold-4','doors':3,'door_list':'Indigenous cultural cosmology and sky narratives, astronomy and sky science, poetry and lyrical narrative','sl':'n/a','rationale':'Three doors: Indigenous cosmology, astronomy, poetry. 326ch at two bands with genuine Indigenous knowledge and astronomical content confirmed.'},
  {'idx':112,'v2':4,'decision':'hold-4','doors':3,'door_list':'bat biology and chiropterology (flight, echolocation, fruiting habits), ecology and food webs, social-emotional (belonging and acceptance of difference)','sl':'n/a','rationale':'Three doors: bat biology, ecology, social-emotional. 237ch at three bands; bat biological content confirmed and cross-domain reach with social-emotional belonging narrative.'},
  {'idx':113,'v2':4,'decision':'hold-4','doors':3,'door_list':'technology biography and Silicon Valley history, American entrepreneurship and innovation history, design philosophy and aesthetics','sl':'n/a','rationale':'Three doors: technology biography, entrepreneurship/innovation history, design philosophy. 233ch single-band biography with three confirmed cross-domain doors.'},
  {'idx':114,'v2':4,'decision':'hold-4','doors':4,'door_list':'folk tale narrative structure and literary craft, food history and culinary culture, community cooperation and social-emotional generosity, European geography and cultural history','sl':'n/a','rationale':'Four doors confirmed by subject tags (geography, language-arts, social-emotional) plus culinary history. 521ch at two bands with four confirmed substantive cross-domain doors.'},
  {'idx':115,'v2':4,'decision':'hold-4','doors':3,'door_list':'outdoor science and environmental education, social-emotional (anxiety, belonging, and finding community), summer camp community dynamics','sl':'n/a','rationale':'Three doors: outdoor science, social-emotional anxiety/belonging, community dynamics. Social-emotional tag confirmed; 310ch at two bands with three confirmed cross-domain doors.'},
  {'idx':116,'v2':4,'decision':'hold-4','doors':3,'door_list':'astronomy and cosmic dust science, philosophy of wonder and human smallness, poetry and lyrical narrative craft','sl':'n/a','rationale':'Three doors: cosmic/astronomical science, philosophical wonder, poetry. 324ch at two bands; sundust concept opens astronomy and philosophy alongside lyrical craft.'},
  {'idx':117,'v2':4,'decision':'hold-4','doors':3,'door_list':'Indigenous traditional craft (leather tanning), environmental science and animal materials, cultural heritage and ecological knowledge','sl':'n/a','rationale':'Three doors: Indigenous craft traditions, materials/environmental science, cultural heritage. 366ch at two bands; tanning process opens genuine craft, materials science, and cultural knowledge doors.'},
  {'idx':118,'v2':4,'decision':'hold-4','doors':3,'door_list':'wildlife biology and bear ecology, wilderness geography and landscape, social-emotional (imagination, wildness, and inner life)','sl':'n/a','rationale':'Three doors: wildlife biology, wilderness geography, social-emotional imagination. 279ch at two young bands with confirmed bear ecology and geography alongside social-emotional content.'},
  {'idx':119,'v2':4,'decision':'hold-4','doors':4,'door_list':'entomology and beetle biology, ecological diversity and biodiversity, scientific illustration as historical documentation and art, natural history','sl':'n/a','rationale':'Four doors confirmed by subject tags (art, science). 526ch rich OD at two bands with four confirmed cross-domain doors in entomology, biodiversity, scientific illustration, and natural history.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch:
        bk = score4[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 4, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'P2 Batch 6 appended: {len(batch)} rows')
holds = sum(1 for b in batch if b['decision']=='hold-4')
drops = sum(1 for b in batch if b['decision']=='drop-to-3')
print(f'  hold-4: {holds} | drop-to-3: {drops}')
