import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score4 = [b for b in data if b['current_score'] == 4]

batch = [
  {'idx':60,'v2':4,'decision':'hold-4','doors':3,'door_list':'poetry craft and literary arts, social-emotional expression and voice, linguistics and language study','sl':'n/a','rationale':'Three doors: poetry craft, social-emotional expression, linguistics. 308ch at two bands; how-to-write format opens three genuine cross-domain doors in literary and linguistic domains.'},
  {'idx':61,'v2':4,'decision':'hold-4','doors':4,'door_list':'fantasy world-building and magical realism, feminist narrative (woman breaking curse), literary craft and narrative structure, social-emotional (courage and self-determination)','sl':'n/a','rationale':'Four doors: fantasy, feminist narrative, literary craft, social-emotional. Language-arts tag confirmed; 348ch single-band fantasy novel with four substantive cross-domain doors.'},
  {'idx':62,'v2':4,'decision':'hold-4','doors':4,'door_list':'Zimbabwean history and geography, epistolary narrative form, global economic inequality, cross-cultural friendship and empathy','sl':'n/a','rationale':'Four doors: Zimbabwean history/geography, epistolary form, global inequality, cross-cultural friendship. Single-band true story of pen pals with four confirmed cross-domain doors.'},
  {'idx':63,'v2':4,'decision':'hold-4','doors':3,'door_list':'cause-and-effect narrative logic, food science and cooking chemistry (maple syrup origins), social-emotional social dynamics','sl':'n/a','rationale':'Three doors: narrative logic/cause-effect, food science (maple syrup), social-emotional. OD confirms maple syrup science and cooking chemistry alongside the narrative structure.'},
  {'idx':64,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'plant biology, ecology and soil science, social-emotional (generosity)','sl':'n/a','rationale':'Three named domains but nearly wordless format with 101ch OD. Without text delivery the content is visual-only; calibrates with board-book level density. Does not confirm three-door threshold.'},
  {'idx':65,'v2':4,'decision':'hold-4','doors':3,'door_list':'freshwater pond ecology and biology, nature poetry and language arts, seasonal cycles and ecological change','sl':'n/a','rationale':'Three doors: pond ecology/biology, nature poetry, seasonal cycles. OD confirms every named animal is real; seasonal arc maps full ecological cycle across two young bands.'},
  {'idx':66,'v2':4,'decision':'hold-4','doors':3,'door_list':'desert ecology and wildlife biology, desert geography and habitat science, poetry and language arts','sl':'n/a','rationale':'Three doors: desert ecology, geography/habitat, poetry. 325ch at two bands; desert science and geography with poetic delivery confirmed.'},
  {'idx':67,'v2':4,'decision':'hold-4','doors':4,'door_list':'Saharan ecology and natural history, African geography and cultural history, poetry and literary craft, cross-cultural perspective and ethnography','sl':'n/a','rationale':'Four doors: Saharan ecology, African geography/cultural history, poetry craft, cross-cultural perspective. 337ch at two bands with four confirmed substantive cross-domain doors.'},
  {'idx':68,'v2':4,'decision':'hold-4','doors':4,'door_list':'literary intertextuality and meta-fiction about reading, fantasy world-building, book history and book arts, social-emotional (family loyalty and sacrifice)','sl':'n/a','rationale':'Four doors: meta-fiction/literary history, fantasy, book arts, social-emotional. Language-arts tag confirmed; 298ch fantasy novel with four confirmed cross-domain doors.'},
  {'idx':69,'v2':4,'decision':'hold-4','doors':3,'door_list':'microbiology and cellular biology, history of science and scientists (invisible world), social-emotional belonging and wonder','sl':'n/a','rationale':'Three doors: microbiology, science history, social-emotional. 287ch at three bands; invisible microscopic world opens genuine science and history-of-discovery doors.'},
  {'idx':70,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (perfectionism and permission to make imperfect art), visual art and creative process','sl':'n/a','rationale':'Two doors: social-emotional growth mindset, visual art. OD confirms single concept (naming the imperfect as valid). Does not reach three-door threshold.'},
  {'idx':71,'v2':4,'decision':'hold-4','doors':3,'door_list':'Caribbean geography and tropical ecology, social-emotional (resilience and community after disaster), environmental science and hurricane science','sl':'n/a','rationale':'Three doors: Caribbean ecology, social-emotional resilience, hurricane/environmental science. 374ch at two bands with genuine cross-domain reach confirmed.'},
  {'idx':72,'v2':4,'decision':'hold-4','doors':3,'door_list':'Korean American cultural identity and bicultural experience, competitive academic culture and school dynamics, social-emotional friendship and rivalry','sl':'n/a','rationale':'Three doors: cultural identity, academic culture, social-emotional. 302ch at two bands; bicultural identity opens three confirmed substantive cross-domain doors.'},
  {'idx':73,'v2':4,'decision':'hold-4','doors':3,'door_list':'pre-verbal communication and language development, urban geography (Brooklyn photography as real-place anchor), social-emotional parent-child dynamics','sl':'n/a','rationale':'Three doors: language development/linguistics, urban geography, social-emotional. OD confirms Brooklyn photographs as real-geography anchor and pre-verbal communication as linguistic domain.'},
  {'idx':74,'v2':4,'decision':'hold-4','doors':4,'door_list':'Indigenous and Native American oral storytelling traditions, frybread history (colonization and forced removal artifact), intergenerational cultural knowledge, intertribal community and identity','sl':'n/a','rationale':'Four doors: Indigenous storytelling traditions, frybread historical/political significance, intergenerational knowledge, intertribal community. 405ch single-band collection with four confirmed substantive doors.'},
  {'idx':75,'v2':4,'decision':'hold-4','doors':3,'door_list':'social-emotional (impulse control, consequence, repair and forgiveness), literacy and letter-writing, school community and teacher relationships','sl':'n/a','rationale':'Three doors: social-emotional arc (impulse-to-repair), literacy/letter-writing, school community. OD confirms full relational rupture arc across three bands; three substantive doors.'},
  {'idx':76,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (kindness and reciprocity), farm animal science and identification','sl':'n/a','rationale':'Two doors: social-emotional (kindness pays dividends), animal science. OD confirms farm animal names are a bonus lesson; single concept with minimal cross-domain reach. Does not reach three-door threshold.'},
  {'idx':77,'v2':4,'decision':'hold-4','doors':3,'door_list':'Canadian historical fiction and social justice history, social-emotional courage and resistance, narrative craft and historical fiction technique','sl':'n/a','rationale':'Three doors: Canadian history, social justice/courage, narrative craft. 329ch at two bands; historical fiction with confirmed social justice content and narrative craft.'},
  {'idx':78,'v2':4,'decision':'hold-4','doors':3,'door_list':'Caribbean and Puerto Rican cultural identity, social-emotional family bonds and intergenerational love, cultural heritage and language','sl':'n/a','rationale':'Three doors: Caribbean cultural identity, social-emotional family bonds, cultural heritage/language. 254ch at two bands with confirmed cultural and intergenerational cross-domain reach.'},
  {'idx':79,'v2':4,'decision':'hold-4','doors':4,'door_list':'physics and materials science (states of matter), chemistry and molecular science, STEM identity and gender (girls in science), narrative humor and science craft','sl':'n/a','rationale':'Four doors: physics/materials science, chemistry, STEM/gender identity, narrative humor. 312ch at two bands; matter science with confirmed cross-domain science and identity reach.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch:
        bk = score4[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 4, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'P2 Batch 4 appended: {len(batch)} rows')
holds = sum(1 for b in batch if b['decision']=='hold-4')
drops = sum(1 for b in batch if b['decision']=='drop-to-3')
print(f'  hold-4: {holds} | drop-to-3: {drops}')
