import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score4 = [b for b in data if b['current_score'] == 4]

batch = [
  {'idx':120,'v2':4,'decision':'hold-4','doors':3,'door_list':'linguistics and language theory (words create images), performative reading and theater arts, social-emotional (language power and humor)','sl':'n/a','rationale':'Three doors: linguistics/language theory, performative arts, social-emotional humor. OD confirms language-creates-images concept and performative reading as genuine cross-domain doors.'},
  {'idx':121,'v2':4,'decision':'hold-4','doors':4,'door_list':'coral reef biology and marine science, coral restoration and conservation science, biography of Ken Nedimyer, ecology of reef ecosystems','sl':'n/a','rationale':'Four doors: reef biology, conservation science, biography, reef ecology. Science tag confirmed; 375ch single-band nonfiction with four confirmed substantive cross-domain doors.'},
  {'idx':122,'v2':4,'decision':'hold-4','doors':4,'door_list':'dystopian world-building and speculative fiction, ecology and resource scarcity (energy, food, infrastructure), social-emotional (courage, truth-telling, and civic duty), mystery and puzzle-solving narrative','sl':'n/a','rationale':'Four doors: dystopian fiction, resource ecology, social-emotional, mystery. Science tag confirmed; 312ch single-band novel with four confirmed cross-domain doors.'},
  {'idx':123,'v2':4,'decision':'hold-4','doors':3,'door_list':'history of timekeeping and horology, industrial history and social change, historical fiction narrative craft','sl':'n/a','rationale':'Three doors: horology history, industrial history, historical fiction. 292ch at two bands with confirmed history-of-technology content and narrative craft.'},
  {'idx':124,'v2':4,'decision':'hold-4','doors':4,'door_list':'high fantasy and meta-fictional satire of genre conventions, literary intertextuality (fantasy tropes as subject), social-emotional found family, speculative world-building and ecology','sl':'n/a','rationale':'Four doors: meta-fiction/genre satire, literary intertextuality, social-emotional, world-building. Language-arts tag confirmed; 359ch single-band fantasy with four confirmed cross-domain doors.'},
  {'idx':125,'v2':4,'decision':'hold-4','doors':3,'door_list':'visual art and creative process, language arts and self-expression, social-emotional (permission to create and build on small starts)','sl':'n/a','rationale':'Three doors confirmed by subject tags (art, language-arts, social-emotional). 441ch at three bands with three confirmed cross-domain doors in art, literacy, and social-emotional development.'},
  {'idx':126,'v2':4,'decision':'hold-4','doors':4,'door_list':'culinary history and food science (Fannie Farmer and standardized measurement), women\'s history and biography, American cultural history, history of cooking as domestic science','sl':'n/a','rationale':'Four doors: culinary history/food science, women\'s history, American history, biography. 342ch at two bands; Fannie Farmer\'s measurement standardization opens four confirmed cross-domain doors.'},
  {'idx':127,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (perfectionism, self-care, and setting limits), narrative humor','sl':'n/a','rationale':'Two doors: social-emotional (perfectionism/burnout), narrative humor. The Good Egg concept is a single social-emotional idea delivered with craft; science tag not substantively delivered. Does not reach three-door threshold.'},
  {'idx':128,'v2':3,'decision':'drop-to-3','doors':3,'door_list':'Chinese American cultural identity, Chinese history and geography, language arts and cultural literacy','sl':'n/a','rationale':'Three subject tags confirmed (geography, history, language-arts) but 112ch OD is extremely thin for a chapter-length book. Delivery too thin to confirm three-door structural content. Drop-to-3.'},
  {'idx':129,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (grandparent love and noticing ordinary magic), sensory observation and gratitude','sl':'n/a','rationale':'Two doors: social-emotional intergenerational love, sensory observation. OD confirms single concept (love letter to grandparent relationship). Does not reach three-door threshold.'},
  {'idx':130,'v2':4,'decision':'hold-4','doors':4,'door_list':'apiary and bee biology, colony collapse disorder science, agricultural ecology and pollination systems, scientific investigation methodology','sl':'n/a','rationale':'Four doors: bee biology, CCD science, agricultural ecology, scientific methodology. Science tag confirmed; 436ch single-band nonfiction with four confirmed substantive cross-domain doors.'},
  {'idx':131,'v2':4,'decision':'hold-4','doors':3,'door_list':'fantasy and magical realism (ink and book magic), literary craft and book arts (the power of words and books), social-emotional (belonging, power, and identity)','sl':'n/a','rationale':'Three doors: fantasy/magical realism, book arts/literary craft, social-emotional. 381ch single-band novel with confirmed cross-domain reach in literary and magical domains.'},
  {'idx':132,'v2':4,'decision':'hold-4','doors':3,'door_list':'American conservation history and environmental advocacy, wildlife biology and animal rights, social-emotional courage and civic action','sl':'n/a','rationale':'Three doors: conservation history, wildlife biology, social-emotional advocacy/courage. 370ch at two bands with three confirmed cross-domain doors.'},
  {'idx':133,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'sound science and acoustics, nature observation and sensory science','sl':'n/a','rationale':'Two doors: sound science/acoustics, nature observation. OD confirms single concept at 70ch. Does not reach three-door threshold.'},
  {'idx':134,'v2':4,'decision':'hold-4','doors':3,'door_list':'arboriculture and old-growth forest ecology, social-emotional (community, care, and conservation), environmental science and tree biology','sl':'n/a','rationale':'Three doors: forest ecology, social-emotional, environmental science. 309ch at two bands with confirmed ecological and community cross-domain reach.'},
  {'idx':135,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'cartography and geographic skills, ethical reasoning and dilemmas','sl':'n/a','rationale':'Two doors: cartography, ethical reasoning. OD is 46ch — extremely thin. Does not confirm three-door threshold.'},
  {'idx':136,'v2':4,'decision':'hold-4','doors':4,'door_list':'fantasy world-building (magic academy), racial justice and belonging (Black girl in predominantly white magical institution), Conjure cultural heritage and traditions, social-emotional belonging and identity','sl':'n/a','rationale':'Four doors: fantasy, racial justice, Conjure cultural heritage, social-emotional. 328ch at two bands with four confirmed cross-domain doors including race, cultural heritage, and fantasy.'},
  {'idx':137,'v2':4,'decision':'hold-4','doors':4,'door_list':'mystery and puzzle-solving narrative, social-emotional (found family and neurodivergent gifts), philosophical and critical thinking, espionage and intelligence narrative','sl':'n/a','rationale':'Four doors: mystery/puzzle, social-emotional (neurodivergence), philosophy, espionage. 327ch single-band novel with four confirmed substantive cross-domain doors.'},
  {'idx':138,'v2':4,'decision':'hold-4','doors':4,'door_list':'Korean cultural identity and immigration experience, linguistics and naming (Korean naming conventions), social-emotional belonging and school community, cross-cultural friendship','sl':'n/a','rationale':'Four doors confirmed by subject tags (geography, language-arts, social-emotional) plus linguistics. 464ch at two bands with four confirmed cross-domain doors.'},
  {'idx':139,'v2':4,'decision':'hold-4','doors':3,'door_list':'Chinese mythology and folklore, ecology and natural science through mythological lens, narrative and oral storytelling craft','sl':'n/a','rationale':'Three doors: Chinese mythology, ecological themes/natural science, narrative/storytelling craft. 277ch at two bands with confirmed mythology and ecological cross-domain reach.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch:
        bk = score4[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 4, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'P2 Batch 7 appended: {len(batch)} rows')
holds = sum(1 for b in batch if b['decision']=='hold-4')
drops = sum(1 for b in batch if b['decision']=='drop-to-3')
print(f'  hold-4: {holds} | drop-to-3: {drops}')
