import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score4 = [b for b in data if b['current_score'] == 4]

batch = [
  {'idx':80,'v2':4,'decision':'hold-4','doors':4,'door_list':'Chinese American cultural identity, family business and economics, social-emotional belonging and heritage, food and culinary cultural history','sl':'n/a','rationale':'Four doors: cultural identity, economics/food culture, social-emotional, culinary heritage. 290ch at two bands; last-chance restaurant narrative opens four confirmed cross-domain doors.'},
  {'idx':81,'v2':4,'decision':'hold-4','doors':4,'door_list':'Kenyan and East African culture and geography, economics of scarcity and generosity, mathematics and counting, social-emotional community and hospitality','sl':'n/a','rationale':'Four doors confirmed by subject tags (geography, math, social-emotional) plus cultural domain. 562ch rich OD at two bands with four confirmed substantive cross-domain doors.'},
  {'idx':82,'v2':4,'decision':'hold-4','doors':4,'door_list':'American racial segregation history, social-emotional (homelessness, belonging, bridge-building), legend and myth narrative structure, urban American geography','sl':'n/a','rationale':'Four doors: racial history, social-emotional, legend/myth structure, urban geography. Newbery Medal single-band novel with four confirmed substantive cross-domain doors.'},
  {'idx':83,'v2':4,'decision':'hold-4','doors':4,'door_list':'community art and mural painting, urban revitalization and geography, social-emotional (beauty and hope in community), Latinx cultural arts','sl':'n/a','rationale':'Four doors confirmed by subject tags (art, geography, social-emotional) plus cultural arts domain. 503ch at three bands with four confirmed cross-domain doors.'},
  {'idx':84,'v2':4,'decision':'hold-4','doors':4,'door_list':'color science and color mixing, social-emotional (belonging, racial identity metaphor), visual art, chemistry and pigment science','sl':'n/a','rationale':'Four doors confirmed by subject tags (art, science, social-emotional) plus color chemistry. 526ch at two young bands with four confirmed cross-domain doors including real color-mixing science.'},
  {'idx':85,'v2':4,'decision':'hold-4','doors':3,'door_list':'Indigenous Cree cultural traditions and oral heritage, astronomy and lunar science, narrative poetry and lyrical craft','sl':'n/a','rationale':'Three doors: Indigenous cultural heritage, astronomy/lunar science, narrative poetry. 325ch at two bands; moon song tradition opens three confirmed cross-domain doors.'},
  {'idx':86,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (sensory experience as emotional vocabulary), Cree and Metis visual culture and arts','sl':'n/a','rationale':'Two doors: social-emotional sensory vocabulary, Indigenous cultural arts. 86ch board book; two confirmed domains only. Does not reach three-door threshold.'},
  {'idx':87,'v2':4,'decision':'hold-4','doors':3,'door_list':'herpetology and snake biology, social-emotional (social anxiety and classroom performance), humor and narrative satire','sl':'n/a','rationale':'Three doors: snake biology, social-emotional, narrative satire. Science tag confirmed; 362ch at two bands with anaconda biology and social anxiety as confirmed cross-domain doors.'},
  {'idx':88,'v2':4,'decision':'hold-4','doors':4,'door_list':'bison ecology and natural history, Great Plains geography and American history, Indigenous Lakota perspectives on wildlife, conservation science','sl':'n/a','rationale':'Four doors: bison ecology, Great Plains history/geography, Indigenous perspectives, conservation. 389ch at two bands with four confirmed substantive cross-domain doors.'},
  {'idx':89,'v2':4,'decision':'hold-4','doors':3,'door_list':'urban forestry and ecology, social-emotional (generational legacy and memory), environmental science and tree planting','sl':'n/a','rationale':'Three doors: urban ecology/botany, social-emotional legacy, environmental science. 304ch at three bands with confirmed ecological and generational cross-domain reach.'},
  {'idx':90,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'creative thinking and imaginative play, social-emotional (independence and self-direction)','sl':'n/a','rationale':'Two doors: creative thinking, social-emotional independence. OD confirms single foundational concept about creative reframing at 111ch. Does not reach three-door threshold.'},
  {'idx':91,'v2':4,'decision':'hold-4','doors':3,'door_list':'marine biology and cephalopod science, Indigenous cultural heritage and worldview, social-emotional coming-of-age and belonging','sl':'n/a','rationale':'Three doors: marine biology, Indigenous cultural heritage, social-emotional. 425ch at two bands with confirmed marine science and cultural heritage cross-domain reach.'},
  {'idx':92,'v2':4,'decision':'hold-4','doors':4,'door_list':'industrial food systems and agriculture, ecology and environmental impact of food production, economics and food politics, biology and nutrition science','sl':'n/a','rationale':'Four doors: food systems/agriculture, ecology/environmental impact, economics/food politics, nutrition biology. Science tag confirmed; young readers edition of Pollan with four confirmed substantive cross-domain doors.'},
  {'idx':93,'v2':4,'decision':'hold-4','doors':3,'door_list':'insect biology and entomology (mayfly life cycle), aquatic ecology and freshwater habitats, poetry and lyrical narrative craft','sl':'n/a','rationale':'Three doors: entomology, aquatic ecology, poetry. 333ch at two bands; mayfly life cycle opens three confirmed natural science and literary doors.'},
  {'idx':94,'v2':4,'decision':'hold-4','doors':3,'door_list':'deep sea and marine biology, ecology and food web of deep ocean, scientific exploration methodology','sl':'n/a','rationale':'Three doors: marine biology, deep-sea ecology/food web, scientific exploration. Science tag confirmed; 285ch at two bands with three confirmed natural science doors.'},
  {'idx':95,'v2':4,'decision':'hold-4','doors':3,'door_list':'linguistics and onomastics (naming conventions across languages), cultural diversity and global heritage, social-emotional (family love and maternal bonds)','sl':'n/a','rationale':'Three doors: linguistics/onomastics, cultural diversity, social-emotional. OD confirms linguistic content (Amma, Ima, Mama across languages) as genuine cross-domain reach.'},
  {'idx':96,'v2':4,'decision':'hold-4','doors':4,'door_list':'history of technology (water clocks and timekeeping), fluid physics and water flow science, economics of family resourcefulness, Mexican and Latinx cultural heritage','sl':'n/a','rationale':'Four doors: horology history, fluid physics, economics, cultural heritage. OD confirms water clock history and physics of water flow alongside economics of the family that makes its own tools.'},
  {'idx':97,'v2':4,'decision':'hold-4','doors':3,'door_list':'fantasy and mythology (phoenix mythology), social-emotional (identity and transformation), visual narrative and graphic form','sl':'n/a','rationale':'Three doors: mythology/fantasy, social-emotional transformation, visual narrative. 318ch at two bands with confirmed cross-domain reach across mythology and identity.'},
  {'idx':98,'v2':4,'decision':'hold-4','doors':4,'door_list':'seed dispersal and plant biology, ecology and food web relationships, nature poetry and language arts, scientific observation methodology','sl':'n/a','rationale':'Four doors confirmed by subject tags (language-arts, science). 479ch at two bands; seed dispersal science opens four confirmed cross-domain doors including ecology, poetry, and scientific observation.'},
  {'idx':99,'v2':4,'decision':'hold-4','doors':3,'door_list':'American frontier and Western history, social-emotional (grief, courage, and trust), survival and adventure narrative','sl':'n/a','rationale':'Three doors: Western/frontier history, social-emotional, survival narrative. 238ch at two bands; frontier setting opens confirmed historical and social-emotional cross-domain doors.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch:
        bk = score4[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 4, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'P2 Batch 5 appended: {len(batch)} rows')
holds = sum(1 for b in batch if b['decision']=='hold-4')
drops = sum(1 for b in batch if b['decision']=='drop-to-3')
print(f'  hold-4: {holds} | drop-to-3: {drops}')
