import csv, json

SWEEP_JSON = r'C:\Users\amyog\Desktop\Wizkoo\exports\sweep_books.json'
OUT_PATH = r'C:\Users\amyog\Desktop\Wizkoo\exports\library_orbital_score_sweep_v2.csv'

with open(SWEEP_JSON, encoding='utf-8') as f:
    data = json.load(f)

score4 = [b for b in data if b['current_score'] == 4]

batch = [
  {'idx':140,'v2':4,'decision':'hold-4','doors':3,'door_list':'visual art from captive animal perspective, animal science and animal rights, literary craft and distinctive narrative voice','sl':'n/a','rationale':'Three doors confirmed by subject tags (art, language-arts, science). Full chapter-length novel; Ivan\'s artistic voice opens three confirmed cross-domain doors despite thin OD.'},
  {'idx':141,'v2':4,'decision':'hold-4','doors':3,'door_list':'elephant biology and wildlife ecology, social-emotional (belonging, adoption, and courage), conservation and animal rights','sl':'n/a','rationale':'Three doors: elephant biology, social-emotional, conservation. 316ch at two bands with confirmed wildlife and social-emotional cross-domain reach.'},
  {'idx':142,'v2':4,'decision':'hold-4','doors':3,'door_list':'ancient world historical fiction, political intrigue and power dynamics in antiquity, adventure narrative craft','sl':'n/a','rationale':'Three doors: ancient historical fiction, political history/power, adventure narrative. 352ch single-band historical fiction with three confirmed cross-domain doors.'},
  {'idx':143,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (self-perception and identity), marine animal names and basic ocean biology','sl':'n/a','rationale':'Two doors: social-emotional (pout-pout self-perception), marine biology (fish species names). 193ch at two young bands; single concept delivered with rhyme. Does not reach three-door threshold.'},
  {'idx':144,'v2':4,'decision':'hold-4','doors':3,'door_list':'social-emotional (bullying, empowerment, and friendship), school community and playground dynamics, narrative humor and character arc','sl':'n/a','rationale':'Three doors: social-emotional (bullying/empowerment), school community, narrative humor. Social-emotional tag confirmed; 254ch at three bands with confirmed cross-domain reach.'},
  {'idx':145,'v2':4,'decision':'hold-4','doors':4,'door_list':'sea turtle biology and life cycle, oceanography and migration science, conservation science and satellite tracking methodology, scientific fieldwork and data collection','sl':'n/a','rationale':'Four doors: turtle biology, oceanography/migration, conservation science, scientific methodology. Science tag confirmed; 313ch at two bands with four confirmed cross-domain doors.'},
  {'idx':146,'v2':4,'decision':'hold-4','doors':3,'door_list':'shrew and small mammal biology, mystery and detective narrative structure, ecology and woodland habitat','sl':'n/a','rationale':'Three doors: animal biology, mystery structure, ecology. 356ch at two bands; shrew detective format opens genuine biology, ecology, and mystery cross-domain doors.'},
  {'idx':147,'v2':4,'decision':'hold-4','doors':4,'door_list':'Maya mythology and cosmology, Guatemalan and Mesoamerican history and geography, disability representation (physical difference), social-emotional belonging and identity','sl':'n/a','rationale':'Four doors: Maya mythology, Mesoamerican history/geography, disability representation, social-emotional. History tag confirmed; 240ch single-band novel with four confirmed cross-domain doors.'},
  {'idx':148,'v2':4,'decision':'hold-4','doors':3,'door_list':'social-emotional (mistakes, resilience, and self-compassion), humor and comedic narrative, school community and friendship dynamics','sl':'n/a','rationale':'Three doors: social-emotional, comedic narrative, school community. Social-emotional tag confirmed; 332ch at two bands with confirmed cross-domain reach.'},
  {'idx':149,'v2':4,'decision':'hold-4','doors':3,'door_list':'comparative mythology (dragon lore across cultures), visual narrative and picture book craft, social-emotional (truth vs. legend and identity)','sl':'n/a','rationale':'Three doors: comparative mythology, visual narrative/picture book craft, social-emotional. 378ch at three bands; cross-cultural dragon myths open genuine comparative mythology domain.'},
  {'idx':150,'v2':4,'decision':'hold-4','doors':3,'door_list':'African savanna ecology and wildlife biology, evolutionary adaptation science, social-emotional (celebrating difference and unconventional beauty)','sl':'n/a','rationale':'Three doors confirmed by subject tags (geography, science, social-emotional). 110ch but three confirmed subjects; African savanna ecology and evolutionary adaptation confirmed as substantive science doors.'},
  {'idx':151,'v2':4,'decision':'hold-4','doors':3,'door_list':'animal communication science (species-specific sounds and mechanisms), vocabulary development and language arts, cumulative narrative structure','sl':'n/a','rationale':'Three doors: animal communication science, vocabulary/language development, cumulative narrative. OD confirms every animal sound as genuine biology; three substantive cross-domain doors at two young bands.'},
  {'idx':152,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'social-emotional (emotional vocabulary and naming feelings), visual art and expressive illustration','sl':'n/a','rationale':'Two doors: emotional vocabulary/social-emotional, visual art. OD confirms single concept (naming emotions); emotional vocabulary development at picture-book density. Does not reach three-door threshold.'},
  {'idx':153,'v2':4,'decision':'hold-4','doors':3,'door_list':'ecology and wildlife biology (AI robot as ecological actor), artificial intelligence and technology ethics, social-emotional (protection, parenthood, and sacrifice)','sl':'n/a','rationale':'Three doors: wildlife ecology, AI ethics/technology, social-emotional. 331ch at two bands; robot-as-ecological-actor opens genuine technology ethics and ecology cross-domain doors.'},
  {'idx':154,'v2':4,'decision':'hold-4','doors':3,'door_list':'magical realism and fantasy (miniature dollhouse world), social-emotional (grief, memory, and family healing), craft and miniature arts','sl':'n/a','rationale':'Three doors: magical realism, social-emotional, miniature craft arts. Social-emotional tag confirmed; 366ch at two bands with confirmed cross-domain reach.'},
  {'idx':155,'v2':4,'decision':'hold-4','doors':4,'door_list':'world geography and global exploration, environmental science and ecology, career awareness in science and exploration, social-emotional curiosity and agency','sl':'n/a','rationale':'Four doors confirmed by subject tags (geography, science, social-emotional). 595ch at two bands with four confirmed cross-domain doors; richly delivered across geography, ecology, and careers.'},
  {'idx':156,'v2':4,'decision':'hold-4','doors':3,'door_list':'visual literacy and narrative reading skills, marine and ocean habitat science, narrative structure and comedic timing','sl':'n/a','rationale':'Three doors: visual literacy, ocean/marine habitat, narrative/comedic structure. OD confirms visual literacy and ocean habitat as genuine cross-domain doors; three substantive doors at three bands.'},
  {'idx':157,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'consumer economics and wants-versus-needs, social-emotional (desire, sacrifice, and friendship)','sl':'n/a','rationale':'Two doors: economics (wants vs. needs), social-emotional. OD confirms single economic concept at 75ch; despite three subject tags the delivery is extremely thin. Does not confirm three-door threshold.'},
  {'idx':158,'v2':3,'decision':'drop-to-3','doors':2,'door_list':'animal science and kitten development biology, scientific observation methodology','sl':'n/a','rationale':'Two doors: kitten biology/animal science, scientific observation. 80ch single-band; kitten rescue as science platform confirms two doors but thin delivery. Does not reach three-door threshold.'},
  {'idx':159,'v2':4,'decision':'hold-4','doors':3,'door_list':'nature observation science (small perfect things in everyday environment), poetry and language arts, social-emotional intergenerational wonder and connection','sl':'n/a','rationale':'Three doors confirmed by subject tags (language-arts, science, social-emotional). 519ch rich OD at two young bands with three confirmed cross-domain doors.'},
]

with open(OUT_PATH, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    for b in batch:
        bk = score4[b['idx']]
        writer.writerow([bk['id'], bk['title'], bk['author'], 4, b['v2'], b['decision'], b['doors'], b['door_list'], b['sl'], b['rationale']])

print(f'P2 Batch 8 appended: {len(batch)} rows')
holds = sum(1 for b in batch if b['decision']=='hold-4')
drops = sum(1 for b in batch if b['decision']=='drop-to-3')
print(f'  hold-4: {holds} | drop-to-3: {drops}')
