import csv, json

BOOKS = [
    {"idx":"J-001","id":"f64f1281-5773-481e-aa59-a2396bb0ff9e","title":"A Seed Grows","author":"Antoinette Portis","year":2022,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The botanical back matter (germination chemistry, photosynthesis, pollination ecology) and fold-out sunflower scale give 7-9 substantive plant science beyond the picture-book surface; each band engages a different depth layer of the same content.","flag":""},
    {"idx":"J-002","id":"61c912a2-2699-4243-907c-9e6899cb2c98","title":"Alexander and the Terrible Horrible No Good Very Bad Day","author":"Judith Viorst","year":1972,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"A fluent 7-9 reader decodes the single-thread emotional narrative in under 5 minutes; the Australian refrain is the only geographic hook and is too thin to constitute a second layer, leaving no substantive content the band hasn't already fully processed.","flag":""},
    {"idx":"J-003","id":"becc0e7e-b20e-4141-8b9c-cd750c8c5ab3","title":"Anything","author":"Rebecca Stead","year":2025,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The mathematical concept of infinity and the philosophical landscape of possibility carry genuine depth for all three bands; the 'how many anythings' spread functions as a visual puzzle 7-9 can engage mathematically while 3-4 experience it as wonder.","flag":""},
    {"idx":"J-004","id":"0b6f5c1e-fb5c-44b3-a092-88c2bd1a4876","title":"At the Window","author":"Hope Lim","year":2025,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The implied-loss narrative and apartment-observation premise are calibrated for the 3-6 emotional range; at 7-9 the friendship-loss-reorientation sequence is processed quickly without a conceptual second layer that justifies the band.","flag":""},
    {"idx":"J-005","id":"6e1f2676-03fb-4c8f-a973-09578100de31","title":"Bartleby","author":"Matt Phelan","year":2026,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Identity formation and resistance to social conformity are authentic 7-9 concerns as peer dynamics intensify; a 7-9 reading about a polar bear refusing to change his essential nature brings real social experience to the text that makes the concept genuinely substantive at this band.","flag":""},
    {"idx":"J-006","id":"9bf459f7-ad66-4fed-a9e8-021ac99d3177","title":"Brave Irene","author":"William Steig","year":1986,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Steig's elevated vocabulary and the genuine weather science (blizzard physics, wind chill, landmark navigation) give 7-9 substantive content beyond the determination narrative; the problem-solving logic when the dress flies away models resourceful reasoning the band can engage critically.","flag":""},
    {"idx":"J-007","id":"0b93858b-1484-42c5-993b-59aa28e6a98c","title":"Chooch Helped","author":"Andrea L. Rogers","year":2024,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The sibling-exhaustion premise is emotionally resonant but concept-thin for 7-9; a fluent reader decodes the entire emotional arc in a single sitting without encountering a second layer that requires the cognitive capacity of this band.","flag":""},
    {"idx":"J-008","id":"25aba46b-c9ce-40d3-be9c-a0e32a8a8c07","title":"Chrysanthemum","author":"Kevin Henkes","year":1991,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"Though the linguistics content (names, etymology, weight of words) gestures toward 7-9 territory, the K-1 mouse-school format and concept depth read as 'for little kids' to a fluent 7-year-old; the name-teasing arc is fully decoded in under 5 minutes with no expanding layer.","flag":""},
    {"idx":"J-009","id":"ad2a033f-c5f0-4e35-bbeb-2e736bbba0f4","title":"Click Clack Moo: Cows That Type","author":"Doreen Cronin","year":2000,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The civics content (collective bargaining, formal written demands, third-party mediation via Duck) and literacy-as-power theme carry genuine substance for all three bands; each band engages a different layer — 3-4 the comedy, 5-6 the writing mechanics, 7-9 the labor-rights structure.","flag":""},
    {"idx":"J-010","id":"059bbc49-9742-4eae-8200-2bbd64e79188","title":"Diary of a Spider","author":"Doreen Cronin","year":2005,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The arachnid biology (webs, molting, silk production) is presented at picture-book density insufficient for 7-9 primary content; the diary format and concept weight are calibrated for 5-6 emerging readers, leaving no second layer for a fluent 7-9 reader.","flag":""},
    {"idx":"J-011","id":"ff3e0389-e6f9-4b05-965b-39e3b5586f77","title":"Diary of a Worm","author":"Doreen Cronin","year":2003,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The soil ecology content (decomposition, earthworm biology) is authentic but presented at early-reader picture-book density; by 7-9 the diary format is familiar and the science is too thinly layered to engage a fluent reader as primary content.","flag":""},
    {"idx":"J-012","id":"684ebd3f-446d-4e68-b20a-dd5fe819d7d9","title":"Doctor De Soto","author":"William Steig","year":1982,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The ethical puzzle (professional duty vs. self-protection, trust violation and premeditated response) engages 7-9 moral reasoning; Steig's elevated vocabulary and the logical elegance of the glue solution reward a fluent reader's analytical attention.","flag":""},
    {"idx":"J-013","id":"1ba03b53-9997-46c0-aa65-c72caef1974c","title":"Don't Eat the Birthday Boy!","author":"Donna Barba Higuera","year":2026,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The impulse-vs.-relationship concept is thinly developed for 7-9; the monster-birthday-party comedy premise delivers the concept at picture-book density without a second layer that justifies the Artisan band.","flag":""},
    {"idx":"J-014","id":"2b0e837b-e50b-40db-8a86-75aedd4f2a23","title":"Don't Trust Fish","author":"Neil Sharpson","year":2025,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The epistemology content (unreliable narration, the difference between assertion and evidence) has genuine educational substance for 7-9 developing critical thinking; 3-4 engage the absurdist fish comedy while 7-9 engage the logic-of-truth-claims layer that underpins it.","flag":""},
    {"idx":"J-015","id":"9ecafe57-379b-4883-a410-b5f095437989","title":"Drum Dream Girl","author":"Margarita Engle","year":2015,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The layered content (Cuban gender history, Afro-Cuban musical tradition, physics of percussion, Caribbean geography, verse poetry structure) gives 7-9 simultaneous academic hooks across history, music, and geography; each band extracts a different primary layer from the same text.","flag":""},
    {"idx":"J-016","id":"aa6d9b53-68b4-4d6f-804d-30858fe9501d","title":"Enemy Pie","author":"Derek Munson","year":2000,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The friendship-mechanics content (proximity and shared play dissolving hostility) is well within a 7-9's existing social understanding; the picture-book format delivers the concept without a second layer, and the father's method reads as charming rather than analytically engaging at this band.","flag":""},
    {"idx":"J-017","id":"2169090a-3ba3-4389-9d59-96a6313928d2","title":"Extra Yarn","author":"Mac Barnett","year":2012,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Barnett's economic concept of abundance (an inexhaustible resource reveals character and transforms community) and the archduke's greed as a lesson in scarcity thinking give 7-9 genuine philosophical content; Klassen's layered visual storytelling rewards careful reading at this band.","flag":""},
    {"idx":"J-018","id":"e616e2ea-24f7-45d4-8767-65b81505b43a","title":"Fireworks","author":"Matthew Burgess","year":2025,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The light physics and urban geography content are present but delivered at visual picture-book density without the concept depth to sustain 7-9 engagement; the Caldecott-winning illustration experience is the primary value, which doesn't substitute for textual or conceptual weight at this band.","flag":""},
    {"idx":"J-019","id":"be1f945f-4b45-4c5e-bd65-232dbd7fbd2c","title":"Fish and Wave","author":"Sergio Ruzzier","year":2022,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader chapter format requires sustained reading comprehension that pre-literate 3-4 cannot follow; the abstract philosophical question of friendship with something always moving also exceeds Wonderer's concrete-operational ceiling.","flag":""},
    {"idx":"J-020","id":"145e26b0-1c36-4a02-886e-8b1583875661","title":"Fox Has a Problem","author":"Corey R. Tabor","year":2023,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader chapter format and the abstract logic of problem-definition (each animal solves the wrong problem) exceed Wonderer's pre-literacy requirement and concrete-operational thinking; the escalating mismatched-solutions structure requires sustained narrative comprehension beyond 3-4 attention span.","flag":""},
    {"idx":"J-021","id":"b5c2d026-d29b-4f9d-b5c2-c24ce733a0fd","title":"Fox Versus Fox","author":"Corey R. Tabor","year":2024,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader format and the abstract identity/authenticity concept (which of two identical characters is 'real'?) both exceed Wonderer's concrete-operational and pre-literacy requirements; the comparison structure presupposes reading ability.","flag":""},
    {"idx":"J-022","id":"fe9950f6-4eab-4252-a098-de25830ae124","title":"Frederick","author":"Leo Lionni","year":1967,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The philosophical question 'what counts as useful labor in a community?' deepens for 7-9 who can engage the economics and ecology of invisible creative work; each reading yields a different layer — 3-4 the mice and seasons, 7-9 the community-utility argument and its answer.","flag":""},
    {"idx":"J-023","id":"a06d73c5-0ef8-4cd0-98b5-1323a742ad62","title":"From Seed to Plant","author":"Gail Gibbons","year":1991,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The labeled-diagram nonfiction format is excellent for 5-6 science learners but underdense for 7-9 who need greater concept depth in plant biology; Gibbons designs this as a foundation text, not a primary resource for fluent readers with developing domain interests.","flag":""},
    {"idx":"J-024","id":"ea2a918c-ba66-4d0b-8035-daa668fade8e","title":"Gigi and Ojiji","author":"Melissa Iwai","year":2022,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader chapter format doesn't support pre-reader engagement; the nonverbal-communication-across-language-barrier concept, while emotionally resonant at all ages, is delivered through a chapter structure that pre-readers cannot independently follow or meaningfully track as a read-aloud.","flag":""},
    {"idx":"J-025","id":"ba0c7b74-edef-46b9-ac5f-5e492144459c","title":"Hair Love","author":"Matthew A. Cherry","year":2019,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The emotional depth of Mom's revealed absence (cancer treatment implied) elevates this beyond a hair-styling story for 7-9; the texture science, Black hair cultural knowledge, and fatherhood-as-practice theme give all three bands substantive content at different registers.","flag":""},
    {"idx":"J-026","id":"7bc55181-dde1-4725-9bf3-d59f4817b557","title":"Henry, Like Always","author":"Jenn Bailey","year":2023,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader chapter format disqualifies Wonderer; the predictable-sequence structure and routine-anxiety content are calibrated for the emerging reader's literacy development and cannot be delivered effectively as a pre-reader read-aloud.","flag":""},
    {"idx":"J-027","id":"6df0d6b8-5528-486b-ac8d-7af57da421ed","title":"Hot Dog","author":"Doug Salati","year":2022,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"Hot Dog is primarily a sensory and emotional experience book; the urban ecology and heat science are present but at visual picture-book surface density, leaving no second layer of conceptual substance for a fluent 7-9 reader who decodes the dog's-eye-view premise quickly.","flag":""},
    {"idx":"J-028","id":"665c09d6-2481-4644-aaa9-8453d527439e","title":"How a House Is Built","author":"Gail Gibbons","year":1990,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The complete technical construction sequence (surveying, foundation, framing, roofing, plumbing, electrical, finishing — each trade named and visualized) carries genuine engineering content across all three bands; 7-9 bring developing systematic thinking to the trade vocabulary and professional sequence.","flag":""},
    {"idx":"J-029","id":"a0a9265c-c1e6-42f8-a89a-d4218e91eac3","title":"How Dinosaurs Went Extinct: A Safety Guide","author":"Ame Dyckman","year":2023,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Real paleontology and mass extinction science (Chicxulub asteroid impact, climate change, food chain collapse) embedded in absurdist safety-poster format gives 7-9 both the comedy structure to appreciate and the genuine science to extract; each band engages a different layer of the same double-coded content.","flag":""},
    {"idx":"J-030","id":"a3ee120a-fd01-4952-8d48-c095a9c4ca8a","title":"How to Count to 1","author":"Casper Salmon","year":2023,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The cardinality and visual-counting concept is foundational mathematics already mastered by 7-9; the mathematical comedy (count one thing in a spread full of many) lands once but offers no expanding layer for a fluent reader with established number sense.","flag":""},
    {"idx":"J-031","id":"1ec03ea0-db35-4e75-b6e0-3a16a9a54ee0","title":"How to Hatch: A Gosling's Guide to Breaking Free","author":"Sara Holly Ackerman","year":2026,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"Pre-reader text density and single-topic biological focus (egg hatching mechanics: air cell, pip reflex, shell-breaking) present real science at a density too thin for 7-9 primary content; the entry-level biology does not expand into the depth 7-9 domain science learners need.","flag":""},
    {"idx":"J-032","id":"941f636f-b69a-400d-a8f4-ccf669a9220e","title":"I Did It!","author":"Michael Emberley","year":2022,"decision":"demote-3-4-and-7-9","new_bands":"5-6","rationale":"Early-reader chapter format disqualifies Wonderer; at 7-9 the simple-sentences/repetition structure and tiny-triumph self-efficacy concept read as calibrated for the 5-6 band — the gap between tiny accomplishment and enormous pride is developmentally a 5-6 insight, not a 7-9 one.","flag":""},
    {"idx":"J-033","id":"ee80fc08-e859-41e1-9112-a219cd469a82","title":"I Hear the Snow, I Smell the Sea","author":"Janice Milusich","year":2025,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader reading level and the abstract sensory neuroscience concept (perceiving the environment differently) exceed Wonderer's concrete-operational requirement; Raschka's expressionist illustration style doesn't provide the sequential visual narrative pre-readers need to follow the story independently.","flag":""},
    {"idx":"J-034","id":"69c7aa1b-e76e-4d86-831f-4e11bf64564b","title":"I Like Myself!","author":"Karen Beaumont","year":2004,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The affirmation-rhyme format and body vocabulary content are calibrated for pre-readers and kindergartners; at 7-9 the concept density and register read as 'for little kids' without a second layer — a fluent reader processes the entire text in under 2 minutes.","flag":""},
    {"idx":"J-035","id":"8bbb56d2-d371-4708-aa59-6fa2c6c27214","title":"Iggy Peck, Architect","author":"Andrea Beaty","year":2007,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Real architecture and landmark references, engineering physics, and art history content give 7-9 substantive academic hooks; Beaty's sophisticated rhyming verse doesn't read as baby-register and the STEM content carries for domain-interested Artisans building on prior knowledge.","flag":""},
    {"idx":"J-036","id":"867cc1c0-1217-4cab-8e58-84b3563a9951","title":"Invisible Things","author":"Andy J. Pizza","year":2023,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The layered invisible-force framework (physics: gravity, magnetism, sound waves; biology: growth, digestion; philosophy: friendship and love) carries genuine concept density for all three bands; 7-9 engage the scientific vocabulary as real science alongside the philosophical dimension.","flag":""},
    {"idx":"J-037","id":"4fe5696f-a74f-4be2-8a83-2bfd6a63a725","title":"Ish","author":"Peter Reynolds","year":2004,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The perfectionism-permission concept is relevant at 7-9 but delivered at picture-book density with no expanding second layer; a fluent reader grasps the 'ish' concept immediately and finds nothing new to extract from the brief text and simple narrative.","flag":""},
    {"idx":"J-038","id":"dd309e54-98ed-48e5-a3ab-16a0542017f8","title":"Lilly's Purple Plastic Purse","author":"Kevin Henkes","year":1996,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The relational rupture arc (impulse → consequence → regret → repair → forgiveness), while emotionally accurate, is compressed into a K-1 mouse picture book that 7-9 readers decode immediately — no conceptual second layer requires this band's cognitive capacity.","flag":""},
    {"idx":"J-039","id":"74adedf5-42d5-44e9-91b7-58f26aa8b2d8","title":"Mama Miti: Wangari Maathai and the Trees of Kenya","author":"Donna Jo Napoli","year":2010,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The layered biography/history/science/geography content (Wangari Maathai's Nobel-winning environmental activism, Kenyan geography, political history of the Green Belt Movement) carries genuine academic depth; 7-9 studying world history and environmental science engage this as primary content.","flag":""},
    {"idx":"J-040","id":"afe8975e-de44-4f66-b232-0a93212ab7ba","title":"Maybe Something Beautiful","author":"F. Isabel Campoy & Theresa Howell","year":2016,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The real-world civic art content (Barrio Logan Urban Art Trail, community organizing as civic infrastructure, color theory as collective action) gives 7-9 substantive content in art history and civics; Lopez's authentic mural illustrations add place-based and art history dimensions.","flag":""},
    {"idx":"J-041","id":"cdafec6b-7f9b-4469-98cc-2ba297387371","title":"Mike Mulligan and His Steam Shovel","author":"Virginia Lee Burton","year":1939,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The economic history content (technological obsolescence, labor displacement by diesel, civic infrastructure investment) and Burton's intricate architectural pen-and-ink illustrations carry genuine historical and engineering substance for 7-9 beyond the machine-story surface.","flag":""},
    {"idx":"J-042","id":"afdd6964-9729-4b39-bc67-7e61f4ec1abd","title":"My Daddy Is a Cowboy","author":"Stephanie Seales","year":2025,"decision":"flag-for-amy","new_bands":"3-4, 5-6, 7-9","rationale":"Empty orbital_description field prevents proper band-fit evaluation; subjects field lists social-emotional only, which suggests the Artisan (7-9) band may be a forced fit, but Amy should confirm concept depth before demoting — specifically whether Black cowboy representation and fatherhood content carry a second layer for 7-9.","flag":"review"},
    {"idx":"J-043","id":"67c7c414-aa58-4089-9c10-479bf96067ab","title":"Nell Plants a Tree","author":"Anne Wynter","year":2023,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The philosophy of planting what you won't see fully grown, multigenerational community history, and forest ecology through a complete tree life cycle carry genuine depth for 7-9; Miyares's time-passage illustrations (changing light and season across generations) are artistically sophisticated.","flag":""},
    {"idx":"J-044","id":"d857f408-25a5-4b40-b85c-2b0847a94aad","title":"Officer Buckle and Gloria","author":"Peggy Rathmann","year":1995,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The trust-collapse and partnership-repair content is genuine but packaged in a K-2 comedy picture book without concept density to engage 7-9; the safety-rule content is calibrated for younger children and a fluent reader fully processes the trust arc in a single sitting.","flag":""},
    {"idx":"J-045","id":"d5fec630-3776-41c7-9ede-018d1df57c84","title":"Once Upon a Book","author":"Grace Lin","year":2023,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Literary self-reference and narrative meta-cognition require an existing reader's relationship to books that pre-literate 3-4 haven't yet formed; the recursive structure (girl enters her own book) lands only once a child already reads and understands books as objects with interiors.","flag":""},
    {"idx":"J-046","id":"c37d386a-384f-4ebc-a192-d022a160982c","title":"Over and Under the Pond","author":"Kate Messner","year":2017,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The above/below pond ecosystem split is an elegant structural concept but is presented at picture-book density insufficient for 7-9; the ecological detail (species listed above and below the water line) doesn't reach the depth a 7-9 science learner needs as primary content.","flag":""},
    {"idx":"J-047","id":"5280e340-b84c-45df-aa64-ab6c93be3436","title":"Owl and Penguin","author":"Vikram Madan","year":2022,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader chapter format disqualifies Wonderer; the nocturnal/diurnal biological conflict is presented through a chapter structure that pre-readers cannot independently follow or sustain as a read-aloud.","flag":""},
    {"idx":"J-048","id":"413fd0ea-1b8e-412e-a3c8-8fb52e1614ea","title":"Owl Moon","author":"Jane Yolen","year":1987,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Yolen's elevated prose style is substantive for 7-9 who can appreciate poetic nature writing as a craft; the winter ecology science (owl species, nocturnal behavior, patient observation as scientific method) and the 'art of stillness' give 7-9 both literary and scientific content.","flag":""},
    {"idx":"J-049","id":"e1799254-5eb7-47d1-80a4-53498c75d9a3","title":"Popo the Xolo","author":"Paloma Angelina Lopez","year":2025,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Aztec underworld mythology and pre-Columbian Mexico geography require prior cultural knowledge that exceeds 3-4's concrete-world frame; the early-reader reading level and mythology layer both push above Wonderer's pre-literacy and concrete-operational requirements.","flag":""},
    {"idx":"J-050","id":"b99bb54f-d140-4be5-9905-868da408ea9d","title":"Rosie Revere, Engineer","author":"Andrea Beaty","year":2013,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The WWII historical context (Rosie the Riveter reference), engineering design cycle (failure as iteration data), and growth mindset philosophy give 7-9 substantive content; Beaty's sophisticated verse and the Great-Great-Aunt Rose biographical anchor carry literary depth beyond the invention comedy.","flag":""},
    {"idx":"J-051","id":"b843eeb9-cbac-46e8-91f8-67528a761b72","title":"Roxaboxen","author":"Alice McLerran","year":1991,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The childhood geography and social-play concepts, while meaningful, are presented at picture-book density; a 7-9 navigating complex real social structures finds the Roxaboxen model (pebbles and broken glass as social architecture) too simplified to engage as primary content.","flag":""},
    {"idx":"J-052","id":"3374fa70-9372-46c2-84a2-d4de5f808858","title":"Sam and Dave Dig a Hole","author":"Mac Barnett","year":2014,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Genuine geological content (underground layers, diamond formation, what lies beneath) paired with Barnett's narratively sophisticated circular ending (the mystery children must solve to understand what happened) gives 7-9 both scientific and literary content; Klassen's illustrations carry visual puzzle depth.","flag":""},
    {"idx":"J-053","id":"fc2b9d38-99f0-470f-8f2f-dc896bb523ee","title":"Stellaluna","author":"Janell Cannon","year":1993,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The bat biology content (echolocation, nocturnal behavior, fruit-eating adaptations) and the biology appendix specifically serve older readers; the identity theme (belonging vs. being yourself) is authentic 7-9 territory as peer pressure intensifies, giving this genuine dual-register substance.","flag":""},
    {"idx":"J-054","id":"3812272a-c4ae-4966-9f81-d93ab32544bd","title":"Stop That Mop!","author":"Jonathan Fenske","year":2025,"decision":"demote-3-4-and-7-9","new_bands":"5-6","rationale":"Early-reader format disqualifies Wonderer; at 7-9 the escalating-comedy cause-and-effect concept and early-reader density are calibrated for the 5-6 band (Geisel Award target: beginning readers), reading as conceptually thin for fluent 7-9 readers who have long internalized compounding-problem narrative structure.","flag":""},
    {"idx":"J-055","id":"32efc50d-50b3-4b06-b7d8-590d66b9e9d8","title":"Sulwe","author":"Lupita Nyong'o","year":2019,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The astronomy content (star formation, light/shadow mechanics in the Day-Night fable), colorism as a social-cultural concept, and Kenyan visual culture through Harrison's illustrations give 7-9 substantive multi-domain content; the cosmological fable is sophisticated enough to carry at this band.","flag":""},
    {"idx":"J-056","id":"75af5533-9a1e-4b78-ac74-82ed89b7d115","title":"Swimmy","author":"Leo Lionni","year":1963,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"Swimmy's ocean ecosystem and schooling-as-defense concept are scientifically accurate but presented at pre-reader picture-book density; the cooperation lesson is familiar territory for 7-9 and the brief text offers no second layer requiring this band's cognitive capacity.","flag":""},
    {"idx":"J-057","id":"ef7c753b-eecf-48fb-a364-2f8eb23b3f2e","title":"The Arguers","author":"Corinna Luyken","year":2025,"decision":"demote-3-4","new_bands":"5-6, 7-9","rationale":"Early-reader reading level and the meta-quality of argument-as-narrative-structure exceed Wonderer's concrete-operational ceiling; the fairy tale logic framing requires genre familiarity pre-readers haven't yet built, making the recursive joke inaccessible at the 3-4 band.","flag":""},
    {"idx":"J-058","id":"22e98cd3-6db4-4346-b4ac-df8b770c97bf","title":"The Day the Crayons Quit","author":"Drew Daywalt","year":2013,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The letter-format persuasive writing structure and color psychology content (each crayon's complaint encodes real color associations: red=overwork, white=invisibility, blue=scale) carry genuine instructional substance for 7-9 writing learners; the professional-communication meta-level lands specifically at this band.","flag":""},
    {"idx":"J-059","id":"51b5caee-1c68-41db-8be6-a053df58b774","title":"The Dot","author":"Peter H. Reynolds","year":2003,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The artistic confidence and color theory content are delivered at picture-book density; a 7-9 grasps the mentorship-and-permission theme immediately and the brief text offers no second conceptual layer to sustain engagement by a fluent reader.","flag":""},
    {"idx":"J-060","id":"7898ea87-a970-4736-aed4-4853c99e7a04","title":"The Keeping Quilt","author":"Patricia Polacco","year":1988,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The multigenerational immigration history, textile arts as memory archive, and Polacco's real family biography give 7-9 substantive content across history, craft, and cultural transmission; each generation adding to the quilt's story models how objects carry history — a genuinely sophisticated concept for this band.","flag":""},
    {"idx":"J-061","id":"7b51ed13-7aff-498d-bef0-5917d58b88fd","title":"The Listening Walk","author":"Paul Showers","year":1991,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The sound physics content is presented at neighborhood-observation level — onomatopoeia and listening attention — insufficient for 7-9; a fluent reader decodes the entire scientific content of the walk in under 4 minutes with no second layer requiring Artisan-level engagement.","flag":""},
    {"idx":"J-062","id":"ef8874ad-9b6f-4064-9066-c6838f9290e4","title":"The Little House","author":"Virginia Lee Burton","year":1942,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"A century of American urbanization (transportation history: horse-to-elevated-train-to-subway, environmental change, urban sprawl and renewal) compressed into a single picture book; Burton's intricate architectural illustrations function as historical documents that reward careful study at 7-9.","flag":""},
    {"idx":"J-063","id":"cb7e34e5-ae22-4901-8833-1632ca317434","title":"The Recess Queen","author":"Alexis O'Neill","year":2002,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The bullying-intervention model (unafraid friendliness, invitation to play) is genuine social psychology but packaged at K-2 picture-book density; a 7-9's actual peer dynamics are more complex than the jump-rope-together solution, and the format reads as 'for little kids' without a second layer.","flag":""},
    {"idx":"J-064","id":"d9e4d160-c321-4088-aa30-6f75fdd9b1cf","title":"The Relatives Came","author":"Cynthia Rylant","year":1985,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The sensory richness of family reunion and Virginia geography are presented at picture-book density without a second layer; the emotional content (summer warmth, ache of goodbye) is accessible but not conceptually engaging for 7-9 as primary content — it reads as nostalgic rather than substantive.","flag":""},
    {"idx":"J-065","id":"a91f8ae6-8fb6-43cd-9181-24d896e9bd19","title":"The Snail and the Whale","author":"Julia Donaldson","year":2003,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"World geography content (icebergs, volcanoes, beaches, coral reefs as named distinct ecosystems) and marine biology (whale stranding and rescue mechanics) give 7-9 substantive geographic and ecological content; Donaldson's sophisticated rhyme carries at this band without baby-register.","flag":""},
    {"idx":"J-066","id":"3063c2bc-0e82-497d-806b-bdb62bcd24ed","title":"The Truth about Dragons","author":"Julie Leung","year":2023,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Comparative mythology (Eastern vs. Western dragon traditions placed side by side) and the epistemological lesson ('truth changes depending on where you stand') are substantive philosophy and world history content; 7-9 engage the comparative analysis most fully as they begin cross-cultural study.","flag":""},
    {"idx":"J-067","id":"5bd407cd-074f-404c-adea-02af3c449cd3","title":"The Ugly Five","author":"Julia Donaldson","year":2017,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The evolutionary adaptation concept (each ugly feature is a survival advantage) is genuine biology but presented at picture-book rhyme density; 7-9 with biology interest will have outpaced this level, and the African savanna geography is listed but not developed deeply enough to carry the band independently.","flag":""},
    {"idx":"J-068","id":"773a213f-f1ed-4df8-9a6a-f400de573c50","title":"The Water Princess","author":"Susan Verde","year":2016,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The memoir-backed water access story carries geography (Burkina Faso), water science (access, contamination, distance-to-source), and social justice content that engages 7-9 across multiple academic domains; the real basis (Georgie Badiel's childhood) gives it biographical and historical weight.","flag":""},
    {"idx":"J-069","id":"81ad82ba-60b4-4d23-b774-cf8839308b6f","title":"The Yellow Bus","author":"Loren Long","year":2024,"decision":"flag-for-amy","new_bands":"3-4, 5-6, 7-9","rationale":"The philosophy-of-purpose content and ecological transformation (bus-as-habitat) could carry genuine depth for 7-9 or read as thin contemplative picture book; 'contemplative ode' descriptions can mean either sparse-text-beautiful-images (demote 7-9) or genuinely philosophical text — Amy should confirm text density before classifying.","flag":"review"},
    {"idx":"J-070","id":"4207d9b3-eb32-454e-84b1-2655737f6804","title":"This Is Not My Hat","author":"Jon Klassen","year":2012,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"Klassen's visual-literary sophistication (the big fish's eyes narrate the true story before text confirms it) gives 7-9 genuine visual literacy content; the dark irony of the small fish's rationalizations and the ocean habitat add scientific and literary layers a fluent reader can analyze.","flag":""},
    {"idx":"J-071","id":"16a917e6-21c1-4d6f-98d7-7db99bd63f3b","title":"Thunder Cake","author":"Patricia Polacco","year":1990,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The meteorology physics (counting seconds between lightning and thunder to calculate storm distance), food science (baking chemistry from scratch), and psychological reframing strategy (purposeful action transforms fear) give 7-9 substantive multi-domain content; Polacco's dense illustration style carries additional observational detail.","flag":""},
    {"idx":"J-072","id":"3f342aec-3941-4d69-ab06-02534d97bcae","title":"Tops and Bottoms","author":"Janet Stevens","year":1995,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The plant science (which edible parts grow above vs. below ground) is foundational knowledge already familiar to 7-9; the Appalachian trickster tale structure is enjoyable but the concept density is calibrated for concrete-operational early-elementary learners rather than fluent Artisan readers.","flag":""},
    {"idx":"J-073","id":"9216b1b4-e511-470d-812b-807dd7074942","title":"Unflappable","author":"Matthew Ward","year":2023,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The engineering design cycle (iterate-fail-learn, each failure informing the next machine) with diagram-specific machine drawings and flightless bird anatomy gives 7-9 substantive STEM content; the persistence psychology is developmentally well-timed as domain interests and performance stakes intensify.","flag":""},
    {"idx":"J-074","id":"e8dab9b4-63ba-485f-8314-e2f09773d625","title":"We Are Water Protectors","author":"Carole Lindstrom","year":2020,"decision":"confirm-triple","new_bands":"3-4, 5-6, 7-9","rationale":"The Indigenous environmental philosophy, Standing Rock historical context, and water science (water as interconnected ecological system) give 7-9 substantive content in environmental science, Indigenous history, and social justice; the Caldecott Medal illustration quality adds visual and cultural depth.","flag":""},
    {"idx":"J-075","id":"e15a32d2-db46-45a1-b7c0-4bd0bc90bde8","title":"Wemberly Worried","author":"Kevin Henkes","year":2000,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"Wemberly's worry inventory is age-calibrated for preschool concerns (radiator, sandbox); at 7-9 anxiety is real but the K-1 picture-book delivery doesn't match the complexity of this band's social landscape, and the format reads as 'for little kids' without a second layer.","flag":""},
    {"idx":"J-076","id":"7fb484a2-68af-4f00-8168-a64ab5a3de94","title":"What Do You Do with a Chance","author":"Kobi Yamada","year":2018,"decision":"demote-7-9","new_bands":"3-4, 5-6","rationale":"The opportunity cost concept and philosophical framing are relevant at 7-9 but delivered at inspirational-picture-book density; the sparse text and social-emotional-only subject framing don't carry sufficient concept weight for 7-9 as primary content — the concept is grasped immediately without an expanding layer.","flag":""},
]

out_path = r"C:\Users\amyog\Desktop\Wizkoo\exports\library_open_item_j_triple_tag_audit.csv"

with open(out_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow([
        "audit_index","id","title","author","year_published",
        "current_bands","decision","new_bands","rationale","beth_review_flag"
    ])
    for b in BOOKS:
        writer.writerow([
            b["idx"], b["id"], b["title"], b["author"], b["year"],
            "3-4, 5-6, 7-9", b["decision"], b["new_bands"],
            b["rationale"], b["flag"]
        ])

print(f"Wrote {len(BOOKS)} rows to {out_path}")

# Tally
from collections import Counter
counts = Counter(b["decision"] for b in BOOKS)
print("Decision counts:")
for k,v in sorted(counts.items()):
    print(f"  {k}: {v}")
print(f"  TOTAL: {sum(counts.values())}")

flags = [b for b in BOOKS if b["flag"]=="review"]
print(f"\nflag-for-amy items ({len(flags)}):")
for b in flags:
    print(f"  {b['idx']} {b['title']} — {b['rationale'][:80]}...")
